CONFIG_IMG_MANAGER=y
CONFIG_IMG_ERASE_PROGRESSIVELY=y

CONFIG_MCUBOOT_SHELL=y
CONFIG_MCUBOOT_IMG_MANAGER=y

CONFIG_STREAM_FLASH=y

CONFIG_ZVFS_OPEN_MAX=24

CONFIG_NVS_INIT_BAD_MEMORY_REGION=y

CONFIG_MAIN_STACK_SIZE=8192
CONFIG_ESPTOOLPY_FLASH_MODE_AUTO_DETECT=n
