/* Autogenerated file. Do not edit manually. */

/* eslint-disable max-classes-per-file */
/* eslint-disable @typescript-eslint/no-unused-vars */
/* eslint-disable @typescript-eslint/consistent-type-imports */

/*
  Fuels version: 0.100.3
  Forc version: 0.67.0
  Fuel-Core version: 0.41.9
*/

import {
  BigNumberish,
  BN,
  decompressBytecode,
  InputValue,
  Predicate as __Predicate,
  PredicateParams,
  Provider,
} from 'fuels';

export type TestPredicateConfigurables = undefined;

export type TestPredicateInputs = [password: BigNumberish];

export type TestPredicateParameters = Omit<
  PredicateParams<TestPredicateInputs, TestPredicateConfigurables>,
  'abi' | 'bytecode'
>;

const abi = {
  "programType": "predicate",
  "specVersion": "1",
  "encodingVersion": "1",
  "concreteTypes": [
    {
      "type": "bool",
      "concreteTypeId": "b760f44fa5965c2474a3b471467a22c43185152129295af588b022ae50b50903"
    },
    {
      "type": "u64",
      "concreteTypeId": "1506e6f44c1d6291cdf46395a8e573276a4fa79e8ace3fc891e092ef32d1b0a0"
    }
  ],
  "metadataTypes": [],
  "functions": [
    {
      "inputs": [
        {
          "name": "password",
          "concreteTypeId": "1506e6f44c1d6291cdf46395a8e573276a4fa79e8ace3fc891e092ef32d1b0a0"
        }
      ],
      "name": "main",
      "output": "b760f44fa5965c2474a3b471467a22c43185152129295af588b022ae50b50903",
      "attributes": [
        {
          "name": "doc-comment",
          "arguments": [
            " This predicate checks if the given password is 1337."
          ]
        },
        {
          "name": "doc-comment",
          "arguments": [
            " If it is, the predicate is 'unlocked' and the transaction is allowed to proceed."
          ]
        },
        {
          "name": "doc-comment",
          "arguments": [
            " Otherwise, it is reverted."
          ]
        }
      ]
    }
  ],
  "loggedTypes": [],
  "messagesTypes": [],
  "configurables": []
};

const bytecode = decompressBytecode('H4sIAAAAAAAAAzVQvUoDQRD+7jx1MadZiEVYmyAWlgFBtNvjEi7EZssrPD07Sw1inVew8Kf0EfYRfAQf4dpAAmkCCSku34bNwrIz8/3MzKp5F29AhO0J8t1b1H+BrGuoqcEHMH7V2HucIS7ubPyUnMNktv3QB0xq2/cJ0OJ915C7fNRD2EoizVpwTUdqhtSfEH+hVpZ9CMadMpGC+aXLOccBeTF5x8Seyxk5Dsus43Y998Zrc5cXqW0U7EdN08XsK856p1qyN2sN1prUCMYBNdp7DLyH8R5HagJ0llfI11Vo1lXEWUKV/uNCA5/A4ZfA9i9U+guVVRgN9m+531gtWF9J/BD/Jm+4BDLuuwH5YnJUWAEAAA==');

export class TestPredicate extends __Predicate<
  TestPredicateInputs,
  TestPredicateConfigurables
> {
  static readonly abi = abi;
  static readonly bytecode = bytecode;

  constructor(params: TestPredicateParameters) {
    super({ abi, bytecode, ...params });
  }
}
