{
  imports = [
    ./atuin.nix
    ./aichat.nix
    ./emacs
    ./bash.nix
    ./bat.nix
    ./btop.nix
    ./chromium.nix
    ./claude-code.nix
    ./clock-rs.nix
    ./command-not-found.nix
    ./direnv.nix
    ./element-desktop.nix
    ./eza.nix
    ./fastfetch
    ./fd.nix
    # ./firefox.nix
    ./fzf.nix
    ./gcc.nix
    ./gh.nix
    ./git.nix
    ./go.nix
    ./gpg.nix
    ./grep.nix
    ./home-manager.nix
    ./hyprland
    ./info.nix
    ./jq.nix
    ./jqp.nix
    ./k9s.nix
    ./kitty
    ./kubecolor.nix
    ./lazydocker.nix
    ./lazygit.nix
    ./lazysql.nix
    ./less.nix
    ./man.nix
    ./mu.nix
    ./neovim
    ./nh.nix
    ./nix-index.nix
    ./nix-search-tv.nix
    ./obs-studio.nix
    ./obsidian.nix
    ./opencode.nix
    ./openstackclient.nix
    ./password-store.nix
    ./pandoc.nix
    ./ripgrep.nix
    ./rtorrent.nix
    ./ssh.nix
    ./sftpman.nix
    ./sketchybar
    ./starship
    ./television.nix
    ./tex-fmt.nix
    ./texlive.nix
    ./tiny.nix
    ./tmux.nix
    ./uv.nix
    ./vim.nix
    ./vivaldi
    ./vscode.nix
    ./yazi.nix
    ./zed.nix
    ./zellij.nix
    ./zoxide.nix
    ./zsh
  ];
}
