;; -*- mode: eask; lexical-binding: t -*-

(package "mcumgr"
         "0.0.1"
         "MCUmgr Toolkit integration for GNU Emacs")

(website-url "https://github.com/MFarabi619/MFarabi619/modules/home/programs/emacs/extra/mcumgr")
(keywords "lisp" "tools")

(package-file "mcumgr.el")

(script "check" "eask lint checkdoc && eask compile && eask clean elc && eask test buttercup")

(development
 (depends-on "buttercup"))
