trunk-version  = "*" # semver version requirement of trunk for this project

[build]
inject_scripts = true
release        = true
dist           = "dist"
minify         = "always"
target         = "index.html"
