INSERT INTO metrics (type, name, unit)
VALUES
    ('sensors.temperature_and_humidity.v1', 'temperature_celsius', 'celsius'),
    ('sensors.temperature_and_humidity.v1', 'relative_humidity_percent', 'percent'),
    ('sensors.wind_speed.v1', 'wind_speed_kilometers_per_hour', 'kilometers_per_hour'),
    ('sensors.wind_direction.v1', 'wind_direction_angle', 'degrees'),
    ('sensors.wind_direction.v1', 'wind_direction_slice', 'slice_index'),
    ('sensors.solar_radiation.v1', 'solar_radiation_watts_per_square_meter', 'watts_per_square_meter'),
    ('sensors.carbon_dioxide.v1', 'co2_ppm', 'ppm'),
    ('sensors.carbon_dioxide.v1', 'temperature', 'celsius'),
    ('sensors.carbon_dioxide.v1', 'humidity', 'percent'),
    ('sensors.soil.v1', 'temperature_celsius', 'celsius'),
    ('sensors.soil.v1', 'moisture_percent', 'percent'),
    ('sensors.soil.v1', 'conductivity', 'conductivity'),
    ('sensors.soil.v1', 'salinity', 'salinity'),
    ('sensors.soil.v1', 'tds', 'tds'),
    ('sensors.current.v1', 'current_mA', 'milliamps'),
    ('sensors.current.v1', 'bus_voltage_V', 'volts'),
    ('sensors.current.v1', 'shunt_voltage_mV', 'millivolts'),
    ('sensors.current.v1', 'power_mW', 'milliwatts'),
    ('sensors.current.v1', 'energy_J', 'joules'),
    ('sensors.current.v1', 'charge_C', 'coulombs'),
    ('sensors.current.v1', 'die_temperature_C', 'celsius'),
    ('sensors.barometric_pressure.v1', 'pressure_hpa', 'hectopascals'),
    ('sensors.barometric_pressure.v1', 'temperature_celsius', 'celsius'),
    ('sensors.rainfall.v1', 'rainfall_millimeters', 'millimeters'),
    ('sensors.power.v1', 'voltage', 'volts'),
    ('sensors.power.v1', 'temperature_celsius', 'celsius'),
    ('status.v1', 'memory_heap', 'bytes'),
    ('status.v1', 'chip_cores', 'count'),
    ('status.v1', 'chip_revision', 'count'),
    ('status.v1', 'wifi_rssi', 'dbm'),
    ('status.v1', 'uptime_seconds', 'seconds')
ON CONFLICT (type, name) DO NOTHING;
