[package]
name = "web"
version = "0.1.0"
authors = ["jet"]
license = "GNU GPL 3.0"
edition = "2021"

[dependencies]
ratatui = { version = "0.29.0", default-features = false }
color-eyre = "0.6.3"
ratzilla = "0.0.4"
