;; -*- mode: eask; lexical-binding: t -*-

(package "tailscale"
         "0.0.1"
         "Tailscale for GNU Emacs")

(website-url "https://github.com/MFarabi619/MFarabi619/modules/home/programs/emacs/extra/tailscale")
(keywords "tools" "comm")

(package-file "tailscale.el")

(script "check" "eask lint checkdoc && eask compile && eask clean elc && eask test buttercup")

(development
 (depends-on "buttercup"))
