use std::{
    collections::HashMap,
    error::Error,
    fs::{self, File},
    io::BufWriter,
    path::Path,
};

use cadrum::{Color, DVec2, DVec3, Mesh, Solid};
use robot_description::{
    datums::{WHEEL_TREAD_DIAMETER_MM, WHEEL_TREAD_WIDTH_MM},
    link::LinkId,
    parameters::{FRAME_LENGTH_MM, FRAME_TOP_Z_MM, FRAME_WIDTH_MM, RAIL_CROSS_HEIGHT_MM},
    placement::CAMERA_OPTICAL_RPY,
    MESH_URI_PREFIX, MM_TO_M,
};

use crate::{
    collada::write_collada,
    config::RobotConfig,
    export::TESSELLATION,
    mass_properties::LinkSummary,
    material::Material,
    Joint, JointType, Link,
};

pub fn drivetrain_params() -> String {
    use robot_description::placement::{wheel_origin, Corner};
    let wheel_radius = WHEEL_TREAD_DIAMETER_MM / 2.0 * MM_TO_M;
    let wheel_separation = 2.0 * wheel_origin(Corner::FrontLeft).y.abs() * MM_TO_M;
    format!(
        r#"# Generated by robot_generator_common from CAD datums — regenerate with `cargo run -p robot_generator_common`.
/**/diff_drive_controller:
  ros__parameters:
    wheel_separation: {wheel_separation:.4}
    wheel_radius: {wheel_radius:.4}
"#
    )
}

fn gz_ros2_control_system(namespace: &str) -> String {
    let namespace_element = if namespace.is_empty() {
        String::new()
    } else {
        format!("        <namespace>{namespace}</namespace>\n")
    };
    format!(
        r#"  <gazebo>
    <plugin filename="gz_ros2_control-system" name="gz_ros2_control::GazeboSimROS2ControlPlugin">
      <parameters>package://robot_control/config/control.yaml</parameters>
      <ros>
{namespace_element}        <remapping>~/cmd_vel:=platform/cmd_vel</remapping>
        <remapping>~/reference:=platform/cmd_vel</remapping>
        <remapping>~/odom:=odom</remapping>
        <remapping>~/odometry:=odom</remapping>
        <remapping>joint_states:=joint_states</remapping>
        <remapping>robot_description:=/robot_description</remapping>
      </ros>
    </plugin>
  </gazebo>

  <gazebo>
    <plugin filename="gz-sim-pose-publisher-system" name="gz::sim::systems::PosePublisher">
      <publish_link_pose>true</publish_link_pose>
      <publish_nested_model_pose>true</publish_nested_model_pose>
      <use_pose_vector_msg>true</use_pose_vector_msg>
      <update_frequency>50</update_frequency>
    </plugin>
  </gazebo>

"#
    )
}

fn ros2_control_block(is_simulation: bool, namespace: &str) -> String {
    let plugin = if is_simulation {
        "gz_ros2_control/GazeboSimSystem"
    } else {
        "robot_hardware_interfaces/DiffDriveHardware"
    };
    let mut block =
        String::from("  <ros2_control name=\"DiffDriveHardware\" type=\"system\">\n    <hardware>\n");
    block.push_str(&format!("      <plugin>{plugin}</plugin>\n"));
    block.push_str("    </hardware>\n");
    for wheel_joint in [
        "front_left_wheel_joint",
        "front_right_wheel_joint",
        "rear_left_wheel_joint",
        "rear_right_wheel_joint",
    ] {
        block.push_str(&format!(
            "    <joint name=\"{wheel_joint}\">\n      <command_interface name=\"velocity\"/>\n      <state_interface name=\"position\"/>\n      <state_interface name=\"velocity\"/>\n    </joint>\n",
        ));
    }
    block.push_str("  </ros2_control>\n\n");
    if is_simulation {
        block.push_str(&gz_ros2_control_system(namespace));
    }
    block
}

const CAMERA_DEFAULT_WIDTH: u32 = 1280;
const CAMERA_DEFAULT_HEIGHT: u32 = 800;
const CAMERA_DEFAULT_FPS: u32 = 30;
const CAMERA_HORIZONTAL_FOV_RAD: f64 = 1.2217;
const DEPTH_CLIP_NEAR_M: f64 = 0.25;
const DEPTH_CLIP_FAR_M: f64 = 20.0;
const IMU_DEFAULT_RATE_HZ: f64 = 25.0;

fn sim_sensor_plugins(config: &RobotConfig) -> String {
    let mut xml = String::new();
    for (index, camera) in config.sensors.camera.iter().enumerate() {
        if !camera.launch_enabled {
            continue;
        }
        let name = format!("camera_{index}");
        let link = format!("camera_{index}_link");
        let optical = format!("camera_{index}_color_optical_frame");
        let parameters = camera
            .ros_parameters
            .get(&name)
            .or_else(|| camera.ros_parameters.values().next());
        let width = parameters
            .and_then(|parameters| parameters.color_width)
            .unwrap_or(CAMERA_DEFAULT_WIDTH);
        let height = parameters
            .and_then(|parameters| parameters.color_height)
            .unwrap_or(CAMERA_DEFAULT_HEIGHT);
        let update_rate = parameters
            .and_then(|parameters| parameters.color_fps)
            .unwrap_or(CAMERA_DEFAULT_FPS);
        let has_depth = parameters.is_some_and(|parameters| parameters.enable_depth);
        let (sensor_type, depth_clip_element) = if has_depth {
            (
                "rgbd_camera",
                format!(
                    "\n        <depth_camera>\n          <clip>\n            <near>{DEPTH_CLIP_NEAR_M}</near>\n            <far>{DEPTH_CLIP_FAR_M}</far>\n          </clip>\n        </depth_camera>"
                ),
            )
        } else {
            ("camera", String::new())
        };
        xml.push_str(&format!(
            r#"  <gazebo reference="{link}">
    <sensor name="{name}" type="{sensor_type}">
      <update_rate>{update_rate}</update_rate>
      <always_on>true</always_on>
      <frame_id>{optical}</frame_id>
      <camera>
        <horizontal_fov>{CAMERA_HORIZONTAL_FOV_RAD}</horizontal_fov>
        <image>
          <width>{width}</width>
          <height>{height}</height>
        </image>
        <clip>
          <near>0.1</near>
          <far>100.0</far>
        </clip>{depth_clip_element}
      </camera>
    </sensor>
  </gazebo>

"#
        ));
    }
    for (index, imu) in config.sensors.imu.iter().enumerate() {
        let update_rate = imu
            .ros_parameters
            .values()
            .next()
            .and_then(|parameters| parameters.rate_hz)
            .unwrap_or(IMU_DEFAULT_RATE_HZ);
        xml.push_str(&format!(
            r#"  <gazebo reference="imu_{index}_link">
    <sensor name="imu_{index}" type="imu">
      <update_rate>{update_rate}</update_rate>
      <always_on>true</always_on>
      <frame_id>imu_{index}_link</frame_id>
    </sensor>
  </gazebo>

"#
        ));
    }
    for _gps in &config.sensors.gps {
        xml.push_str(
            r#"  <gazebo reference="gps_link">
    <sensor name="gps" type="navsat">
      <always_on>1</always_on>
      <update_rate>1</update_rate>
      <frame_id>gps_link</frame_id>
    </sensor>
  </gazebo>

"#,
        );
    }
    xml
}

const ORBBEC_GEMINI_335L_MODEL: &str = "orbbec_gemini_335l";
const ORBBEC_GEMINI_335L_MESH: &str = "orbbec_gemini_335l.dae";
const ORBBEC_GEMINI_335L_STL: &str = "orbbec-gemini-335l.stl";
// Visual origin and color from orbbec_description gemini_335_L_336_L.urdf.xacro (camera_link).
const ORBBEC_GEMINI_335L_MESH_OFFSET: DVec3 = DVec3::new(-0.011715, -0.0475, -0.014311);
const ORBBEC_GEMINI_335L_COLOR: Color = Color {
    r: 0.792157,
    g: 0.819608,
    b: 0.933333,
};

const STL_HEADER_BYTES: usize = 80;
const STL_TRIANGLE_COUNT_BYTES: usize = 4;
const STL_TRIANGLE_BYTES: usize = 50;
const STL_NORMAL_BYTES: usize = 12;
const STL_VERTEX_BYTES: usize = 12;

fn read_binary_stl_corners(path: &Path) -> Result<Vec<DVec3>, Box<dyn Error>> {
    let bytes = fs::read(path)?;
    let triangle_count = u32::from_le_bytes(
        bytes[STL_HEADER_BYTES..STL_HEADER_BYTES + STL_TRIANGLE_COUNT_BYTES].try_into()?,
    ) as usize;
    let triangles_offset = STL_HEADER_BYTES + STL_TRIANGLE_COUNT_BYTES;
    let mut corners = Vec::with_capacity(triangle_count * 3);
    for triangle_index in 0..triangle_count {
        let triangle = &bytes[triangles_offset + triangle_index * STL_TRIANGLE_BYTES..];
        for corner_index in 0..3 {
            let vertex = &triangle[STL_NORMAL_BYTES + corner_index * STL_VERTEX_BYTES..];
            corners.push(DVec3::new(
                f32::from_le_bytes(vertex[0..4].try_into()?) as f64,
                f32::from_le_bytes(vertex[4..8].try_into()?) as f64,
                f32::from_le_bytes(vertex[8..12].try_into()?) as f64,
            ));
        }
    }
    Ok(corners)
}

fn orbbec_gemini_335l_mesh() -> Result<Mesh, Box<dyn Error>> {
    let corners = read_binary_stl_corners(&crate::mesh(ORBBEC_GEMINI_335L_STL))?;
    let mut vertices: Vec<DVec3> = Vec::new();
    let mut vertex_index_by_position: HashMap<[u64; 3], usize> = HashMap::new();
    let mut indices = Vec::with_capacity(corners.len());
    for corner in corners {
        let position = corner + ORBBEC_GEMINI_335L_MESH_OFFSET;
        let key = [
            position.x.to_bits(),
            position.y.to_bits(),
            position.z.to_bits(),
        ];
        let index = *vertex_index_by_position.entry(key).or_insert_with(|| {
            vertices.push(position);
            vertices.len() - 1
        });
        indices.push(index);
    }
    let triangle_count = indices.len() / 3;
    Ok(Mesh {
        uvs: vec![DVec2::ZERO; vertices.len()],
        vertices,
        indices,
        face_ids: vec![0; triangle_count],
        colormap: HashMap::from([(0, ORBBEC_GEMINI_335L_COLOR)]),
        edges: Vec::new(),
    })
}

fn sensor_and_mount_frames(config: &RobotConfig) -> String {
    let mut xml = String::new();
    for mount in &config.mounts.camera_mount {
        push_frame(
            &mut xml,
            "camera_mount_link",
            &mount.parent,
            mount.xyz,
            mount.rpy,
        );
    }
    for (index, camera) in config.sensors.camera.iter().enumerate() {
        let link = format!("camera_{index}_link");
        let optical = format!("camera_{index}_color_optical_frame");
        if camera.model == ORBBEC_GEMINI_335L_MODEL {
            push_mesh_frame(
                &mut xml,
                &link,
                &camera.parent,
                camera.xyz,
                camera.rpy,
                ORBBEC_GEMINI_335L_MESH,
            );
        } else {
            push_frame(&mut xml, &link, &camera.parent, camera.xyz, camera.rpy);
        }
        // ROS REP-103 optical convention: rotate x-forward body frame into z-forward optical frame.
        push_frame(&mut xml, &optical, &link, [0.0; 3], CAMERA_OPTICAL_RPY);
    }
    for gps in &config.sensors.gps {
        push_frame(&mut xml, LinkId::GpsLink.link_name(), &gps.parent, gps.xyz, gps.rpy);
    }
    for (index, imu) in config.sensors.imu.iter().enumerate() {
        push_frame(&mut xml, &format!("imu_{index}_link"), &imu.parent, imu.xyz, imu.rpy);
    }
    xml
}

fn push_frame(xml: &mut String, name: &str, parent: &str, xyz: [f64; 3], rpy: [f64; 3]) {
    xml.push_str(&format!("  <link name=\"{name}\"/>\n"));
    push_fixed_joint(xml, name, parent, xyz, rpy);
}

fn push_mesh_frame(
    xml: &mut String,
    name: &str,
    parent: &str,
    xyz: [f64; 3],
    rpy: [f64; 3],
    mesh_filename: &str,
) {
    xml.push_str(&format!(
        "  <link name=\"{name}\">\n    <visual><geometry><mesh filename=\"{MESH_URI_PREFIX}{mesh_filename}\"/></geometry></visual>\n  </link>\n",
    ));
    push_fixed_joint(xml, name, parent, xyz, rpy);
}

fn push_fixed_joint(xml: &mut String, child: &str, parent: &str, xyz: [f64; 3], rpy: [f64; 3]) {
    xml.push_str(&format!("  <joint name=\"{child}_joint\" type=\"fixed\">\n"));
    xml.push_str(&format!("    <parent link=\"{parent}\"/>\n"));
    xml.push_str(&format!("    <child link=\"{child}\"/>\n"));
    xml.push_str(&format!(
        "    <origin xyz=\"{:.4} {:.4} {:.4}\" rpy=\"{:.4} {:.4} {:.4}\"/>\n",
        xyz[0], xyz[1], xyz[2], rpy[0], rpy[1], rpy[2],
    ));
    xml.push_str("  </joint>\n\n");
}

pub fn write(
    links: &[Link],
    joints: &[Joint],
    summaries: &[LinkSummary],
    config: &RobotConfig,
    robot: &str,
    package_directory: &Path,
) -> Result<(), Box<dyn Error>> {
    let meshes_directory = package_directory.join("meshes");
    if meshes_directory.exists() {
        for entry in fs::read_dir(&meshes_directory)? {
            let path = entry?.path();
            if matches!(
                path.extension().and_then(|ext| ext.to_str()),
                Some("stl" | "glb" | "dae")
            ) {
                fs::remove_file(&path)?;
            }
        }
    } else {
        fs::create_dir_all(&meshes_directory)?;
    }

    let camera_mesh = orbbec_gemini_335l_mesh()?;
    let mut camera_mesh_writer =
        BufWriter::new(File::create(meshes_directory.join(ORBBEC_GEMINI_335L_MESH))?);
    write_collada(&camera_mesh, Material::pbr_for_rgb, &mut camera_mesh_writer)?;

    let mut body = String::new();
    body.push_str(&format!(
        "  <link name=\"{}\"/>\n\n",
        LinkId::BaseLink.link_name()
    ));

    for link in links {
        body.push_str(&format!("  <link name=\"{}\">\n", link.id.link_name()));
        if !link.solids.is_empty() {
            let mesh_filename = format!("{}.dae", link.id.link_name());
            let local_solids: Vec<Solid> = link
                .solids
                .iter()
                .map(|solid| {
                    solid
                        .clone()
                        .translate(-link.origin_world)
                        .scale(DVec3::ZERO, MM_TO_M)
                })
                .collect();
            let mesh = Solid::mesh(&local_solids, TESSELLATION)?;
            let mut writer = BufWriter::new(File::create(meshes_directory.join(&mesh_filename))?);
            write_collada(&mesh, Material::pbr_for_rgb, &mut writer)?;
            body.push_str(&format!(
                "    <visual><geometry><mesh filename=\"{MESH_URI_PREFIX}{mesh_filename}\"/></geometry></visual>\n",
            ));
        }
        if let Some(collision) = collision_xml(link.id) {
            body.push_str(&collision);
        }
        if link.id != LinkId::Chassis {
            if let Some(inertial) = summaries
                .iter()
                .find(|summary| summary.id == link.id)
                .and_then(inertial_xml)
            {
                body.push_str(&inertial);
            }
        }
        body.push_str("  </link>\n");
    }
    body.push('\n');

    if let Some(inertial) = summaries
        .iter()
        .find(|summary| summary.id == LinkId::Chassis)
        .and_then(inertial_xml)
    {
        body.push_str("  <link name=\"inertial_link\">\n");
        body.push_str(&inertial);
        body.push_str("  </link>\n");
        body.push_str(
            "  <joint name=\"inertial_joint\" type=\"fixed\">\n    <parent link=\"chassis\"/>\n    <child link=\"inertial_link\"/>\n    <origin xyz=\"0 0 0\" rpy=\"0 0 0\"/>\n  </joint>\n\n",
        );
    }

    for joint in joints {
        write_joint_xml(&mut body, joint, links);
    }
    body.push_str(&sensor_and_mount_frames(config));

    let header = "<?xml version=\"1.0\"?>\n<?xml-model href=\"https://raw.githubusercontent.com/ros/urdfdom/master/xsd/urdf.xsd\" ?>\n<robot name=\"robot\">\n\n";
    let namespace = &config.system.namespace;
    let hardware_urdf = format!(
        "{header}{body}{}</robot>\n",
        ros2_control_block(false, namespace)
    );
    let simulation_urdf = format!(
        "{header}{body}{}{}</robot>\n",
        sim_sensor_plugins(config),
        ros2_control_block(true, namespace)
    );

    let urdf_directory = package_directory.join("urdf").join(robot);
    fs::create_dir_all(&urdf_directory)?;
    fs::write(urdf_directory.join("robot.urdf"), hardware_urdf)?;
    fs::write(urdf_directory.join("robot.sim.urdf"), simulation_urdf)?;
    Ok(())
}

fn collision_xml(id: LinkId) -> Option<String> {
    match id {
        LinkId::WheelFrontLeft
        | LinkId::WheelFrontRight
        | LinkId::WheelRearLeft
        | LinkId::WheelRearRight => Some(format!(
            "    <collision><origin rpy=\"{:.4} 0 0\"/><geometry><cylinder radius=\"{:.4}\" length=\"{:.4}\"/></geometry></collision>\n",
            std::f64::consts::FRAC_PI_2,
            WHEEL_TREAD_DIAMETER_MM / 2.0 * MM_TO_M,
            WHEEL_TREAD_WIDTH_MM * MM_TO_M,
        )),
        LinkId::Chassis => Some(format!(
            "    <collision><origin xyz=\"0 0 {:.4}\"/><geometry><box size=\"{:.4} {:.4} {:.4}\"/></geometry></collision>\n",
            (FRAME_TOP_Z_MM - RAIL_CROSS_HEIGHT_MM / 2.0) * MM_TO_M,
            FRAME_LENGTH_MM * MM_TO_M,
            FRAME_WIDTH_MM * MM_TO_M,
            RAIL_CROSS_HEIGHT_MM * MM_TO_M,
        )),
        _ => None,
    }
}

fn inertial_xml(summary: &LinkSummary) -> Option<String> {
    if summary.mass <= 0.0 {
        return None;
    }
    let origin = summary.center_local;
    let inertia = summary.inertia;
    Some(format!(
        concat!(
            "    <inertial>\n",
            "      <origin xyz=\"{:.4} {:.4} {:.4}\"/>\n",
            "      <mass value=\"{:.4}\"/>\n",
            "      <inertia ixx=\"{:.6e}\" ixy=\"{:.6e}\" ixz=\"{:.6e}\" iyy=\"{:.6e}\" iyz=\"{:.6e}\" izz=\"{:.6e}\"/>\n",
            "    </inertial>\n",
        ),
        origin.x,
        origin.y,
        origin.z,
        summary.mass,
        inertia.x_axis.x,
        inertia.y_axis.x,
        inertia.z_axis.x,
        inertia.y_axis.y,
        inertia.z_axis.y,
        inertia.z_axis.z,
    ))
}

fn write_joint_xml(xml: &mut String, joint: &Joint, links: &[Link]) {
    let child_origin_world = links
        .iter()
        .find(|link| link.id == joint.child)
        .expect("joint child must correspond to a Link in `links`")
        .origin_world;
    // Parent may be base_link (not present in `links`, assume world origin).
    let parent_origin_world = links
        .iter()
        .find(|link| link.id == joint.parent)
        .map(|link| link.origin_world)
        .unwrap_or(DVec3::ZERO);
    let joint_origin_meters = (child_origin_world - parent_origin_world) * MM_TO_M;
    let joint_type_name = match joint.joint_type {
        JointType::Fixed => "fixed",
        JointType::Continuous => "continuous",
    };
    xml.push_str(&format!(
        "  <joint name=\"{}\" type=\"{}\">\n",
        joint.name, joint_type_name
    ));
    xml.push_str(&format!(
        "    <parent link=\"{}\"/>\n",
        joint.parent.link_name()
    ));
    xml.push_str(&format!(
        "    <child link=\"{}\"/>\n",
        joint.child.link_name()
    ));
    let rpy = joint.rpy.unwrap_or([0.0; 3]);
    xml.push_str(&format!(
        "    <origin xyz=\"{:.4} {:.4} {:.4}\" rpy=\"{:.4} {:.4} {:.4}\"/>\n",
        joint_origin_meters.x, joint_origin_meters.y, joint_origin_meters.z, rpy[0], rpy[1], rpy[2],
    ));
    if let Some(axis) = joint.axis {
        xml.push_str(&format!(
            "    <axis xyz=\"{:.1} {:.1} {:.1}\"/>\n",
            axis.x, axis.y, axis.z,
        ));
    }
    xml.push_str("  </joint>\n\n");
}
