;; -*- mode: eask; lexical-binding: t -*-

(package "microvisor"
         "0.0.1"
         "Project task and service orchestration for GNU Emacs")

(website-url "https://github.com/MFarabi619/MFarabi619/modules/home/programs/emacs/extra/microvisor")
(keywords "lisp" "tools" "convenience")

(package-file "microvisor.el")

(script "check" "eask lint checkdoc && eask compile && eask clean elc && eask test buttercup")

(development
 (depends-on "buttercup"))
