serial_number: robot-0005
version: 1
system:
  namespace: robot5
  hosts:
    - hostname: macos
      ip: 127.0.0.1
      board: macos
platform:
  attachments: []
  drivetrain:
    model: odrive_usb
    max_linear_velocity_mps: 2.0
    gear_ratio: 8.0
    left:
      serial: 9779026C334D
      reversed: true
    right:
      serial: 7442026C334D
      reversed: false
sensors:
  camera:
    - model: oak_d_pro_w_poe
      parent: base_link
      xyz: [0.575, 0.5, 0.31]
      rpy: [0.0, 0.0, 0.0]
      ros_parameters:
        camera_0:
          ip: 10.0.0.206
