# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, modulesPath, ... }:

{
  imports =
    [ (modulesPath + "/installer/scan/not-detected.nix")
    ];

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
  hardware={
  cpu.amd.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
  };

  boot={
  initrd={
  availableKernelModules = [ "nvme" "xhci_pci" "thunderbolt" "usbhid" ];
 kernelModules = [ ];
 };
  kernelModules = [ "kvm-amd" ];
  extraModulePackages = [ ];
 };

  fileSystems={
  "/" =
    { device = "/dev/disk/by-uuid/a8dff594-8f16-4347-bb8d-a4029f5e6027";
      fsType = "ext4";
    };

  "/boot" =
    { device = "/dev/disk/by-uuid/28C3-87D9";
      fsType = "vfat";
      options = [ "fmask=0077" "dmask=0077" ];
    };

  "/mnt" =
    { device = "/dev/disk/by-uuid/609d136a-bed9-4ce2-88cc-ae592cfd2adf";
      fsType = "btrfs";
    };

  "/mnt/boot" =
    { device = "/dev/disk/by-uuid/A666-299D";
      fsType = "vfat";
      options = [ "fmask=0022" "dmask=0022" ];
    };
    };

  swapDevices =
    [ { device = "/dev/disk/by-uuid/e3fd1e67-0b6a-4424-a307-937792946690"; }
    ];

  # Enables DHCP on each ethernet and wireless interface. In case of scripted networking
  # (the default) this is the recommended approach. When using systemd-networkd it's
  # still possible to use this option, but it's recommended to use it in conjunction
  # with explicit per-interface declarations with `networking.interfaces.<interface>.useDHCP`.
  networking={
  useDHCP = lib.mkDefault true;
  # interfaces.wlo1.useDHCP = lib.mkDefault true;
  };
}
