
[workspace]
resolver = '2'
members = [
	'apps/web',
	'apps/learning/rust',
	'libs/learning/rust/cats',
	'apps/readme',
]
exclude = [
	'apps/learning/fuel/counter-contract',
]

[profile.release]
lto = true
