[workspace]
preview = ["pixi-build"]
channels = ["https://prefix.dev/conda-forge"]
requires-pixi = ">=0.72.2"
platforms = [{ platform = "linux-64", glibc = "2.34" }, "osx-arm64"]

[dependencies]
make = "*"
cmake = "*"
ninja = "*"
python = "*"
compilers = "*"
pkg-config = "*"
colcon-common-extensions = "*"

[target]
linux-64.dependencies.libgl-devel = "*"

[environments]
default.features = ["lyrical"]

[feature.lyrical]
channels = ["https://prefix.dev/robostack-lyrical"]

[feature.lyrical.dependencies]
ros-lyrical-desktop-full = "*"
