[platformio]
name              = microvisor
default_envs      = ceratina

lib_dir           = libs
src_dir           = firmware/src
test_dir          = firmware/tests
data_dir          = firmware/data
boards_dir        = firmware/machine

[env]
framework         = arduino
platform          = https://github.com/pioarduino/platform-espressif32.git#develop

# targets           =  upload, monitor
lib_ldf_mode      = chain
lib_compat_mode   = strict
lib_deps          =
  adafruit/RTClib@2.1.4
  mobizt/ReadyMail@^0.3.8
  ewpa/LibSSH-ESP32@5.8.0
  robtillaart/TCA9548@^0.3.1
  robtillaart/CHT832X@^0.4.0
  bblanchon/ArduinoJson@7.4.3
  lennarthennigs/ESP Telnet@2.2.3
  adafruit/Adafruit BusIO@^1.17.2
  sensirion/Sensirion Core@^0.7.3
  adafruit/Adafruit ADS1X15@^2.6.2
  adafruit/Adafruit NeoPixel@^1.15.4
  esp32async/ESPAsyncWebServer@3.10.3
  sensirion/Sensirion I2C SCD30@^1.0.0
  sensirion/Sensirion I2C SCD4x@^1.0.0
  https://github.com/stefangs/arduino-library-at24cxxx.git#1.2.2

build_src_filter  = +<*>, -<*.rs>, -<.git/>, -<.svn/>, -<**/*.rs>

upload_speed      = 921600
upload_port       = /dev/cu.usbserial-10
# upload_port       = /dev/cu.usbmodem-10

# upload_port       = 10.0.0.201
# upload_port       = rfc2217://rpi5-16:2217?ign_set_control

monitor_speed     = 115200
monitor_filters   = direct

test_build_src    = true
test_framework    = custom
test_port         = ${env.upload_port}
test_speed        = ${env.monitor_speed}

[env:ceratina]
board_build.filesystem  = littlefs
board_build.f_flash     = 80000000L
board_build.f_cpu       = 240000000L
board_build.arduino.memory_type = qio_opi
board                   = esp32-s3-devkitc1-n8r8

build_flags             =
  -DBOARD_HAS_PSRAM
  # -DCORE_DEBUG_LEVEL=5
  # -DARDUINO_USB_MODE=1
  # -DARDUINO_USB_CDC_ON_BOOT=1
  -DCONFIG_ASYNC_TCP_RUNNING_CORE=1
  -DCONFIG_FREERTOS_USE_TRACE_FACILITY=1
  -DCONFIG_FREERTOS_USE_STATS_FORMATTING_FUNCTIONS=1
  '-DCONFIG_WIFI_SSID="${sysenv.WIFI_SSID}"'
  '-DCONFIG_WIFI_PASS="${sysenv.WIFI_PASSWORD}"'
