# [[file:CONTRIBUTING.org::*platformio][platformio:1]]
[platformio]
name         = microvisor
default_envs = ceratina

lib_dir      = libs
test_dir     = test
data_dir     = firmware/data

[env]
framework         =  arduino
platform          =  espressif32

monitor_echo      =  True

lib_ldf_mode      =  chain
lib_compat_mode   =  strict

# monitor_speed     =  115200
# monitor_rts       =  0
# monitor_dtr       =  0
# monitor_port      =  /dev/cu.usbmodem101
# monitor_filters   =  direct

# test_speed        =  115200
upload_speed      =  921600
build_src_filter  =  +<*>, -<*.rs>, -<.git/>, -<.svn/>, -<**/*.rs>

[env:ceratina]
board                   =  esp32-s3-devkitc-1
board_build.filesystem  =  littlefs
# build_flags             =
#   -DARDUINO_USB_MODE=1
#   -DMONITOR_SPEED=115200
#   -DARDUINO_USB_CDC_ON_BOOT=1

#   -DCONFIG_HTTP_DEBUG_ENABLED=0

#   -DCONFIG_WIFI_OTA_ENABLED=1
#   -DCONFIG_WIFI_OTA_TIMEOUT_MS=10000
#   -DCONFIG_WIFI_CONNECT_TIMEOUT_MS=15000
#   -DCONFIG_WIFI_DEFAULT_HOSTNAME=\"ceratina\"

#   -DCONFIG_NTP_SYNC_TIMEOUT_MS=5000
#   -DCONFIG_NTP_SYNC_POLL_DELAY_MS=100
#   -DCONFIG_NTP_SERVER=\"pool.ntp.org\"
#   -DCONFIG_NTP_TIMEZONE_INFO=\"EST5EDT,M3.2.0/2,M11.1.0/2\"

#   -DCONFIG_SMTP_PORT=1025
#   -DCONFIG_SMTP_SSL_ENABLED=0
#   -DCONFIG_SMTP_TEST_ENABLED=1
#   -DCONFIG_SMTP_AUTH_ENABLED=0
#   -DCONFIG_SMTP_STARTTLS_ENABLED=0
#   -DCONFIG_SMTP_LOGIN_EMAIL=\"\"
#   -DCONFIG_SMTP_HOST=\"10.0.0.198\"
#   -DCONFIG_SMTP_DOMAIN=\"localhost\"
#   -DCONFIG_SMTP_FROM_NAME=\"ceratina\"
#   -DCONFIG_SMTP_NOTIFY=\"SUCCESS,FAILURE,DELAY\"
#   -DCONFIG_SMTP_SUBJECT_PREFIX=\"[ceratina-test]\"
#   -DCONFIG_SMTP_TO_EMAIL=\"farabi@apidaesystems.ca\"
#   -DCONFIG_SMTP_FROM_EMAIL=\"ceratina-test@apidaesystems.local\"

#   -DCONFIG_WEBHOOK_ENABLED=0
#   -DCONFIG_WEBHOOK_URL=\"\"
#   -DCONFIG_WEBHOOK_DEBUG_ENABLED=1
#   -DCONFIG_WEBHOOK_TIMEOUT_MS=7000
#   -DCONFIG_WEBHOOK_METHOD=\"POST\"
#   -DCONFIG_WEBHOOK_AVATAR_URL=\"\"
#   -DCONFIG_WEBHOOK_AUTH_HEADER=\"\"
#   -DCONFIG_WEBHOOK_MAX_RESPONSE_BYTES=512
#   -DCONFIG_WEBHOOK_USERNAME=\"ceratina\"
#   -DCONFIG_WEBHOOK_CONTENT_PREFIX=\"[ceratina]\"
#   -DCONFIG_WEBHOOK_CONTENT_TYPE=\"application/json\"

#   -DCONFIG_I2C_BUS_0_SDA_GPIO=15
#   -DCONFIG_I2C_BUS_0_SCL_GPIO=16
#   -DCONFIG_I2C_BUS_1_SDA_GPIO=17
#   -DCONFIG_I2C_BUS_1_SCL_GPIO=18
#   -DCONFIG_I2C_INIT_DELAY_MS=1000
#   -DCONFIG_I2C_FREQUENCY_HZ=100000

#   -DCONFIG_RELAY_MOSFET_POWER_GPIO_PIN=5
#   -DCONFIG_RS485_CHANNEL_COUNT=2
#   -DCONFIG_RS485_BUS_0_TX_GPIO=45
#   -DCONFIG_RS485_BUS_0_RX_GPIO=48
#   -DCONFIG_RS485_BUS_0_DE_RE_GPIO=47
#   -DCONFIG_RS485_BUS_0_BAUD_RATE=9600
#   -DCONFIG_RS485_BUS_1_TX_GPIO=40
#   -DCONFIG_RS485_BUS_1_RX_GPIO=39
#   -DCONFIG_RS485_BUS_1_DE_RE_GPIO=41
#   -DCONFIG_RS485_BUS_1_BAUD_RATE=4800

#   -DCONFIG_SOIL_PROBE_COUNT=20
#   -DCONFIG_SOIL_LAST_SLAVE_ID=72
#   -DCONFIG_SOIL_FIRST_SLAVE_ID=53
#   -DCONFIG_SOIL_PROBE_DELAY_MS=50

#   -DCONFIG_MODULE_WIND_SPEED_SLAVE_ID=20
#   -DCONFIG_MODULE_WIND_SPEED_RS485_CHANNEL=0
#   -DCONFIG_MODULE_WIND_SPEED_REGISTER_ADDRESS=0

#   -DCONFIG_WIND_SENSOR_DELAY_MS=100

#   -DCONFIG_MODULE_WIND_DIRECTION_SLAVE_ID=1
#   -DCONFIG_MODULE_WIND_DIRECTION_RS485_CHANNEL=0
#   -DCONFIG_MODULE_WIND_DIRECTION_REGISTER_ADDRESS=0

#   -DCONFIG_MODULE_SOLAR_RADIATION_SLAVE_ID=40
#   -DCONFIG_MODULE_SOLAR_RADIATION_RS485_CHANNEL=0
#   -DCONFIG_MODULE_SOLAR_RADIATION_REGISTER_ADDRESS=0

#   -DCONFIG_MODULE_CURRENT_MONITOR_SHUNT_RESISTANCE_OHMS=0.015
#   -DCONFIG_MODULE_CURRENT_MONITOR_MAX_EXPECTED_CURRENT=10.0

#   -DCONFIG_TEMPERATURE_AND_HUMIDITY_0_I2C_ADDRESS=68
#   -DCONFIG_TEMPERATURE_AND_HUMIDITY_1_I2C_ADDRESS=68
#   -DCONFIG_TEMPERATURE_AND_HUMIDITY_RESET_GPIO_PIN=4
# platformio:1 ends here
