[platformio]
name         = microvisor
default_envs = ceratina

lib_dir      = libs
test_dir     = tests
data_dir     = firmware/data

[env]
framework         = arduino
platform          = espressif32

# targets           =  upload, monitor
lib_ldf_mode      = chain
lib_compat_mode   = strict
lib_deps          =
  ewpa/LibSSH-ESP32@5.8.0
  marcinbor85/MicroShell@0.1.0
  esp32async/ESPAsyncWebServer@^3.9.0
  northernwidget/DS3231@^1.1.2
  robtillaart/TCA9548@^0.3.1

build_src_filter  = +<*>, -<*.rs>, -<.git/>, -<.svn/>, -<**/*.rs>

monitor_speed     = 115200
upload_port       = /dev/cu.usbserial-110
monitor_filters   = direct

upload_speed      = 921600

test_build_src    = true
test_framework    = custom
test_port         = ${env.upload_port}
test_speed        = ${env.monitor_speed}

[env:ceratina]
# board_build.flash_mode  = qio
board_build.filesystem  = littlefs
# board_build.f_flash     = 80000000L
board_build.f_cpu       = 240000000L
# board_build.arduino.memory_type = qio_opi
board                   = esp32-s3-devkitc-1

build_flags             =
  '-DCONFIG_SSH_USER="${sysenv.USER}"'
  # -DBOARD_HAS_PSRAM
  # -DARDUINO_USB_MODE=1
  # -DARDUINO_USB_CDC_ON_BOOT=1
  # -mfix-esp32-psram-cache-issue
  # -DCORE_DEBUG_LEVEL=5
