[toolchain]
channel = "esp"

targets = [
    # "i686-linux-android",
    # "x86_64-linux-android",
    # "aarch64-linux-android",
    "wasm32-unknown-unknown",
    # "armv7-linux-androideabi",
]

components = ["rust-src", "rustfmt", "clippy", "rust-analyzer"]
