manifest:
    remotes:
        - name: zephyrproject
          url-base: https://github.com/zephyrproject-rtos

    projects:
        - name: zephyr-lang-rust
          remote: zephyrproject
          revision: main
          path: vendor/modules/lang/rust

        - name: zephyr
          remote: zephyrproject
          revision: f1ff557f96f74a6d82d8b290bc4488ee5f93c483 # main~2: before HAL CS timing regression
          import:
              path-prefix: vendor
              name-allowlist:
                  # ESP32
                  - hal_espressif
                  - hal_xtensa
                  # STM32
                  - hal_stm32
                  - hal_st
                  # Core
                  - cmsis
                  - cmsis_6
                  - mbedtls
                  - mbedtls-3.6
                  - mcuboot
                  - tf-psa-crypto
                  # Filesystems
                  - fatfs
                  - littlefs
                  # Libraries
                  - libmetal
                  - segger
                  - mipi-sys-t
                  - picolibc
                  # Debug
                  - percepio
                  - net-tools

    self:
        path: .
