;; -*- mode: eask; lexical-binding: t -*-

(package "process-compose"
         "0.0.1"
         "Process Compose integration")

(website-url "https://github.com/MFarabi619/MFarabi619/modules/home/programs/emacs/extra/process-compose")
(keywords "tools" "processes")

(package-file "process-compose.el")

(script "check" "eask lint checkdoc && eask compile && eask clean elc && eask test buttercup")

(development
 (depends-on "buttercup"))
