manifest:
    projects:
        - name: nuttx
          revision: nuttx-12.13.0
          path: nuttxspace/nuttx
          url: https://github.com/apache/nuttx

        - name: nuttx-apps
          revision: nuttx-12.13.0
          path: nuttxspace/apps
          url: https://github.com/apache/nuttx-apps
