substitutions:
  hostname: esp32s3-devkitc-1
  use_address: 100.127.251.3

api:
  encryption:
    key: !secret esp32s3-devkitc-1

<<:
  - !include ../../libs/esphome/ota.yaml
  - !include ../../libs/esphome/wifi.yaml
  - !include ../../libs/esphome/esp32.yaml
  - !include ../../libs/esphome/psram.yaml
  - !include ../../libs/esphome/logger.yaml
  - !include ../../libs/esphome/default.yaml
  - !include ../../libs/esphome/tailscale.yaml
  - !include ../../libs/esphome/web_server.yaml
