substitutions:
  hostname: xiao-esp32s3
  # use_address: 100.72.169.123

api:
  encryption:
    key: !secret xiao-esp32s3

<<:
  - !include ../../libs/esphome/ota.yaml
  - !include ../../libs/esphome/wifi.yaml
  - !include ../../libs/esphome/esp32.yaml
  - !include ../../libs/esphome/psram.yaml
  - !include ../../libs/esphome/logger.yaml
  - !include ../../libs/esphome/default.yaml
  - !include ../../libs/esphome/tailscale.yaml
  - !include ../../libs/esphome/web_server.yaml
