[package]
name = "tasks"
version = "0.1.0"
edition = "2024"

[dependencies]
anyhow = "1.0.100"
headless_chrome = {git = "https://github.com/rust-headless-chrome/rust-headless-chrome", features = ["fetch"]}
