name: Generate Readme

on:
  push:
    branches: main

  workflow_dispatch: # Allow for manual triggering

jobs:
  generate_readme:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          ref: ${{ github.head_ref }}

      - name: Install Python
        uses: actions/setup-python@v5

      - name: Display Python version
        run: python -c "import sys; print(sys.version)"

      - name: Run Python script
        run: pwd; python generate_readme.py

      - uses: stefanzweifel/git-auto-commit-action@v5
        with:
            commit_message: "docs: Automatically Update README"
