#+title: The Rust Programming Language

/by Steve labnik, carol Nichols, and Chris Krycho, with contributions from the Rust Community/

This version of the text assumes you’re using Rust 1.90.0 (released 2025-09-18) or later with =edition = "2024"= in the /Cargo.toml/ file of all projects to configure them to use Rust 2024 Edition idioms. See the [[*Installation][“Installation” section of Chapter 1]] for instructions on installing or updating Rust, and see [[*E - Editions][Appendix E]] for information on editions.

The HTML format is available online at https://doc.rust-lang.org/stable/book/ and offline with installations of Rust made with =rustup=; run =rustup doc --book= to open.

Several community [[*F - Translations of the Book][translations]] are also available.

This text is available in [[https://nostarch.com/rust-programming-language-3e][paperback and ebook format from No Starch Press]].

#+begin_quote
🚨 Want a more interactive learning experience?

Try the Rust Book with quizzes, highlighting, and more:
https://rust-book.cs.brown.edu
#+end_quote

- *Foreward*

  The Rust programming language has come a long way in a few short years, from its creation and incubation by a small and nascent community of enthusiasts, to becoming one of the most loved and in-demand programming languages in the world. Looking back, it was inevitable that the power and promise of Rust would turn heads and gain a foothold in systems programming. What was not inevitable was the global growth in interest and innovation that permeated through open source communities and catalyzed wide-scale adoption across industries.

  At this point in time, it is easy to point to the wonderful features that Rust has to offer to explain this explosion in interest and adoption. Who doesn’t want memory safety, and fast performance, and a friendly compiler, and great tooling, among a host of other wonderful features? The Rust language you see today combines years of research in systems programming with the practical wisdom of a vibrant and passionate community. This language was designed with purpose and crafted with care, offering developers a tool that makes it easier to write safe, fast, and reliable code.

  But what makes Rust truly special is its roots in empowering you, the user, to achieve your goals. This is a language that wants you to succeed, and the principle of empowerment runs through the core of the community that builds, maintains, and advocates for this language. Since the previous edition of this definitive text, Rust has further developed into a truly global and trusted language. The Rust Project is now robustly supported by the Rust Foundation, which also invests in key initiatives to ensure that Rust is secure, stable, and sustainable.

  This edition of The Rust Programming Language is a comprehensive update, reflecting the language’s evolution over the years and providing valuable new information. But it is not just a guide to syntax and libraries—it’s an invitation to join a community that values quality, performance, and thoughtful design. Whether you’re a seasoned developer looking to explore Rust for the first time or an experienced Rustacean looking to refine your skills, this edition offers something for everyone.

  The Rust journey has been one of collaboration, learning, and iteration. The growth of the language and its ecosystem is a direct reflection of the vibrant, diverse community behind it. The contributions of thousands of developers, from core language designers to casual contributors, are what make Rust such a unique and powerful tool. By picking up this book, you’re not just learning a new programming language—you’re joining a movement to make software better, safer, and more enjoyable to work with.

  Welcome to the Rust community!

   * Bec Rumbul, Executive Director of the Rust Foundation

- *Introduction*

#+begin_quote
Note: This edition of the book is the same as [[https://nostarch.com/rust-programming-language-3e][The Rust Programming Language]] available in print and ebook format from [[https://nostarch.com][No Starch Press]].
#+end_quote

Welcome to /The Rust Programming Language/, an introductory book about Rust. The Rust programming language helps you write faster, more reliable software. High-level ergonomics and low-level control are often at odds in programming language design; Rust challenges that conflict. Through balancing powerful technical capacity and a great developer experience, Rust gives you the option to control low-level details (such as memory usage) without all the hassle traditionally associated with such control.

*Who Rust Is For*

Rust is ideal for many people for a variety of reasons. Let’s look at a few of the most important groups.

*Teams of Developers*

Rust is proving to be a productive tool for collaborating among large teams of developers with varying levels of systems programming knowledge. Low-level code is prone to various subtle bugs, which in most other languages can only be caught through extensive testing and careful code review by experienced developers. In Rust, the compiler plays a gatekeeper role by refusing to compile code with these elusive bugs, including concurrency bugs. By working alongside the compiler, the team can spend its time focusing on the program’s logic rather than chasing down bugs.

Rust also brings contemporary developer tools to the systems programming world:

 * Cargo, the included dependency manager and build tool, makes adding, compiling, and managing dependencies painless and consistent across the Rust ecosystem.
 * The =rustfmt= formatting tool ensures a consistent coding style across developers.
 * The Rust Language Server powers integrated development environment (IDE) integration for code completion and inline error messages.

By using these and other tools in the Rust ecosystem, developers can be productive while writing systems-level code.

*Students*

Rust is for students and those who are interested in learning about systems concepts. Using Rust, many people have learned about topics like operating systems development. The community is very welcoming and happy to answer students’ questions. Through efforts such as this book, the Rust teams want to make systems concepts more accessible to more people, especially those new to programming.

*Companies*

Hundreds of companies, large and small, use Rust in production for a variety of tasks, including command line tools, web services, DevOps tooling, embedded devices, audio and video analysis and transcoding, cryptocurrencies, bioinformatics, search engines, Internet of Things applications, machine learning, and even major parts of the Firefox web browser.

*Open Source Developers*

Rust is for people who want to build the Rust programming language, community, developer tools, and libraries. We’d love to have you contribute to the Rust language.

*People Who Value Speed and Stability*

Rust is for people who crave speed and stability in a language. By speed, we mean both how quickly Rust code can run and the speed at which Rust lets you write programs. The Rust compiler’s checks ensure stability through feature additions and refactoring. This is in contrast to the brittle legacy code in languages without these checks, which developers are often afraid to modify. By striving for zero-cost abstractions—higher-level features that compile to lower-level code as fast as code written manually—Rust endeavors to make safe code be fast code as well.

The Rust language hopes to support many other users as well; those mentioned here are merely some of the biggest stakeholders. Overall, Rust’s greatest ambition is to eliminate the trade-offs that programmers have accepted for decades by providing safety and productivity, speed and ergonomics. Give Rust a try, and see if its choices work for you.

*Who This Book Is For*

This book assumes that you’ve written code in another programming language, but it doesn’t make any assumptions about which one. We’ve tried to make the material broadly accessible to those from a wide variety of programming backgrounds. We don’t spend a lot of time talking about what programming is or how to think about it. If you’re entirely new to programming, you would be better served by reading a book that specifically provides an introduction to programming.

*How to Use This Book*

In general, this book assumes that you’re reading it in sequence from front to back. Later chapters build on concepts in earlier chapters, and earlier chapters might not delve into details on a particular topic but will revisit the topic in a later chapter.

You’ll find two kinds of chapters in this book: concept chapters and project chapters. In concept chapters, you’ll learn about an aspect of Rust. In project chapters, we’ll build small programs together, applying what you’ve learned so far. Chapter 2, Chapter 12, and Chapter 21 are project chapters; the rest are concept chapters.

[[*Getting Started][Chapter 1]] explains how to install Rust, how to write a “Hello, world!” program, and how to use Cargo, Rust’s package manager and build tool. [[*Programming a Guessing Game][Chapter 2]] is a hands-on introduction to writing a program in Rust, having you build up a number-guessing game. Here, we cover concepts at a high level, and later chapters will provide additional detail. If you want to get your hands dirty right away, Chapter 2 is the place for that. If you’re a particularly meticulous learner who prefers to learn every detail before moving on to the next, you might want to skip Chapter 2 and go straight to [[* Common Programming Concepts][Chapter 3]], which covers Rust features that are similar to those of other programming languages; then, you can return to Chapter 2 when you’d like to work on a project applying the details you’ve learned.

In [[* Understanding Ownership][Chapter 4]], you’ll learn about Rust’s ownership system. [[*Using Structs to Structure Related Data][Chapter 5]] discusses structs and methods. [[*Enums and Pattern Matching][Chapter 6]] covers enums, =match= expressions, and the =if let= and =let...else= control flow constructs. You’ll use structs and enums to make custom types.

In [[Packages, Crates, and Modules][Chapter 7]], you’ll learn about Rust’s module system and about privacy rules for organizing your code and its public application programming interface (API). [[*Common Collections][Chapter 8]] discusses some common collection data structures that the standard library provides: vectors, strings, and hash maps. [[*Error Handling][Chapter 9]] explores Rust’s error-handling philosophy and techniques.

[[Generic Types, Traits, and Lifetimes][Chapter 10]] digs into generics, traits, and lifetimes, which give you the power to define code that applies to multiple types. [[*Writing Automated Tests][Chapter 11]] is all about testing, which even with Rust’s safety guarantees is necessary to ensure that your program’s logic is correct. In [[*An I/O Project: Building a Command Line Program][Chapter 12]], we’ll build our own implementation of a subset of functionality from the grep command line tool that searches for text within files. For this, we’ll use many of the concepts we discussed in the previous chapters.

[[*Functional Language Features: Iterators and Closures][Chapter 13]] explores closures and iterators: features of Rust that come from functional programming languages. In [[*More about Cargo and Crates.io][Chapter 14]], we’ll examine Cargo in more depth and talk about best practices for sharing your libraries with others. [[*Smart Pointers][Chapter 15]] discusses smart pointers that the standard library provides and the traits that enable their functionality.

In [[*Fearless Concurrency][Chapter 16]], we’ll walk through different models of concurrent programming and talk about how Rust helps you program in multiple threads fearlessly. In [[*Fundamentals of Asynchronous Programming: Async, Await, Futures, and Streams][Chapter 17]], we build on that by exploring Rust’s async and await syntax, along with tasks, futures, and streams, and the lightweight concurrency model they enable.

[[*Object Oriented Programming Features][Chapter 18]] looks at how Rust idioms compare to object-oriented programming principles you might be familiar with. [[*Patterns and Matching][Chapter 19]] is a reference on patterns and pattern matching, which are powerful ways of expressing ideas throughout Rust programs. [[*Advanced Features][Chapter 20]] contains a smorgasbord of advanced topics of interest, including unsafe Rust, macros, and more about lifetimes, traits, types, functions, and closures.

In [[Final Project: Building a Multithreaded Web Server][Chapter 21]], we’ll complete a project in which we’ll implement a low-level multithreaded web server!

Finally, some appendixes contain useful information about the language in a more reference-like format. [[*A - Keywords][Appendix A]] covers Rust’s keywords, [[*B - Operators and Symbols][Appendix B]] covers Rust’s operators and symbols, [[*C - Derivable Traits][Appendix C]] covers derivable traits provided by the standard library, [[*Useful Development Tools][Appendix D]] covers some useful development tools, and [[*E - Editions][Appendix E]] explains Rust editions. In [[*F - Translations of the Book][Appendix F]], you can find translations of the book, and in [[*G - How Rust is Made and "Nightly Rust"][Appendix G]] we’ll cover how Rust is made and what nightly Rust is.

There is no wrong way to read this book: If you want to skip ahead, go for it! You might have to jump back to earlier chapters if you experience any confusion. But do whatever works for you.


An important part of the process of learning Rust is learning how to read the error messages the compiler displays: These will guide you toward working code. As such, we’ll provide many examples that don’t compile along with the error message the compiler will show you in each situation. Know that if you enter and run a random example, it may not compile! Make sure you read the surrounding text to see whether the example you’re trying to run is meant to error. In most situations, we’ll lead you to the correct version of any code that doesn’t compile. Ferris will also help you distinguish code that isn’t meant to work:

| *Ferris* | *Meaning*                                          |
|--------+--------------------------------------------------|
|        | This code does not compile!                      |
|        | This code panics!                                |
|        | This code does not produce the desired behavior. |

*Source Code*

The source files from which this book is generated can be found on [[https://github.com/rust-lang/book/tree/main/src][GitHub]].

* Getting Started

Let’s start your Rust journey! There’s a lot to learn, but every journey starts somewhere. In this chapter, we’ll discuss:

 * Installing Rust on Linux, macOS, and Windows
 * Writing a program that prints =Hello, world!=
 * Using =cargo=, Rust’s package manager and build system

** Installation
** Hello, World!
** Hello, Cargo!

* Programming a Guessing Game

#+BEGIN_SRC toml
[package]
name = "guessing_game"
version = "0.1.0"
edition = "2024"
# edition.workspace = true

[dependencies]
rand = "0.9.0"

[workspace]
#+END_SRC

#+BEGIN_SRC rust
use std::cmp::Ordering;
use std::io;
use rand::Rng;

fn main() {
  println!("Guess the number!");

  let secret_number =
    rand::thread_rng().gen_range(1..=100);

  // println!("The secret number is: {secret_number}");

  loop  {
  println!("Please input your guess.");

  let mut guess = String::new();

  io::stdin()
    .read_line(&mut guess)
    .expect("Failed to read line");

  let guess: u32 = match guess
    .trim()
    .parse(){
      Ok(num) => num,
      Err(_) => continue
    };

  println!("You guessed: {guess}");

  match guess.cmp(&secret_number){
    Ordering::Less => println!("Too small!"),
    Ordering::Greater => println!("Too big!"),
    Ordering::Equal => {
      println!("You win!");
      break;
  }
  }
  }
}
#+END_SRC
* Common Programming Concepts
** Variables and Mutability

#+BEGIN_SRC rust
use std::io;

#[allow(unused)]
fn main() {
    let x = 5;

    let x = x + 1;

    {
        let x = x * 2;
        println!("The value of x in the inner scope is: {x}");
    }

    println!("The value of x is: {x}");

    let spaces = "   ";
    let spaces = spaces.len();
    println!("Length of spaces is: {spaces}");

    let guess: u32 = "42".parse().expect("Not a number!");

    let x = 2.0; // f64
    let y: f32 = 3.0; // f32

    // addition
    let sum = 5 + 10;

    // subtraction
    let difference = 95.5 - 4.3;

    // multiplication
    let product = 4 * 30;

    // division
    let quotient = 56.7 / 32.2;
    let truncated = -5 / 3; // Results in -1

    // remainder
    let remainder = 43 % 5;

    let t = true;
    let f: bool = false; // with explicit type annotation

    let c = 'z';
    let z: char = 'Z'; // with explicit type annotation
    let heart_eyed_cat = '😻';

    let tup: (i32, f64, u8) = (500, 6.4, 1);
    println!("{:?}", tup);

    let tup = (500, 6.4, 1);

    let (x, y, z) = tup;

    println!("The value of y is: {y}");

    let x: (i32, f64, u8) = (500, 6.4, 1);

    let five_hundred = x.0;

    let six_point_four = x.1;

    let one = x.2;

    let a = [1, 2, 3, 4, 5];

    let months = [
        "January",
        "February",
        "March",
        "April",
        "May",
        "June",
        "July",
        "August",
        "September",
        "October",
        "November",
        "December",
    ];

    let a: [i32; 5] = [1, 2, 3, 4, 5];

    let a = [3; 5]; // 3, 3, 3, 3, 3

    let first = a[0];
    let second = a[1];

    // invalid array element access
    let a = [1, 2, 3, 4, 5];

    println!("Please enter an array index.");

    let mut index = String::new();

    io::stdin()
        .read_line(&mut index)
        .expect("Failed to read line");

    let index: usize = index
        .trim()
        .parse()
        .expect("Index entered was not a number");

    let element = a[index];

    println!("The value of the element at index {index} is: {element}");
#+END_SRC

** Functions

#+BEGIN_SRC rust
fn main() {
    println!("Hello, world!");

    another_function();
    print_labeled_measurement(5, 'h');
    an_expression();
    // statement_to_another_variable_wont_compile();
    statement_to_expression();

    let x = five();

    println!("The value of x is: {x}");

    let x = plus_one(5);

    println!("The value of x is: {x}");
}

fn another_function() {
    println!("Another function.");
}

fn print_labeled_measurement(value: i32, unit_label: char) {
    println!("The measurement is: {value}{unit_label}")
}

fn an_expression() {
    let y = 6;
}

// fn statement_to_another_variable_wont_compile(){
//   let x = (let y =6);
// }

fn statement_to_expression() {
    let y = {
        let x = 3;
        x + 1
        // expressions don't include ending semicolons
        // adding a semicolor to the end of an expression turns it into a statement, which will not return a value
    };

    println!("The value of y is: {y}")
}

fn five() -> i32 {
    5
}

fn plus_one(x: i32) -> i32 {
    x + 1
}
#+END_SRC

** Comments

#+BEGIN_SRC rust
  #![allow(unused)]
  fn main() {
      // hello, world

      // So we're doing something complicated here, long enough that we need
      // multiple lines of comments to do it! Whew! Hopefully, this comment will
      // explain what's going on.

      let lucky_number = 7; // I'm feeling lucky today

      // I'm feeling lucky today
      let another_lucky_number = 7;
  }
#+END_SRC

** Control Flow

#+BEGIN_SRC rust
  fn if_expressions() {
      let number = 3;

      if number < 5 {
          println!("condition was true");
      } else {
          println!("condition was false");
      }

      let number = 7;

      if number < 5 {
          println!("condition was true");
      } else {
          println!("condition was false");
      }

      let number = 3;
      if number != 0 {
          println!("number was something other than zero");
      }
  }

  fn handling_multiple_conditions_with_else_if() {
      let number = 6;

      if number % 4 == 0 {
          println!("number is divisible by 4");
      } else if number % 3 == 0 {
          println!("number is divisible by 3");
      } else if number % 2 == 0 {
          println!("number is divisible by 2");
      } else {
          println!("number is not divisible by 4, 3, or 2");
      }
  }

  fn using_if_in_a_let_statement() {
      let condition = true;
      let number = if condition { 5 } else { 6 };

      println!("The value of number is: {number}");
  }

  fn repetition_with_loops() {
      loop {
          println!("again!");
      }
  }

  fn returning_values_from_loops() {
      let mut counter = 0;

      let result = loop {
          counter += 1;

          if counter == 10 {
              break counter * 2;
          }
      };

      println!("The result is {result}")
  }

  fn loop_labels_to_disambiguate_between_multiple_loops() {
      let mut count = 0;

      'counting_up: loop {
          println!("count = {count}");
          let mut remaining = 10;

          loop {
              println!("remaining = {remaining}");
              if remaining == 9 {
                  break;
              }
              if count == 2 {
                  break 'counting_up;
              }
              remaining -= 1;
          }
          count += 1;
      }
      println!("End count = {count}");
  }

  fn conditional_loops_with_while() {
      let mut number = 3;

      while number != 0 {
          println!("{number}!");
          number -= 1;
      }

      println!("LIFTOFF!!!");
  }

  fn looping_through_a_collection_with_for() {
      let a = [10, 20, 30, 40, 50];
      let mut index = 0;

      while index < 5 {
          println!("the value is: {}", a[index]);

          index += 1;
      }

      // more concise with for loop
      for element in a {
          println!("the value is: {element}");
      }
  }

  fn convert_temperature_between_fahrenheit_and_celcius() {
      loop {
          println!("Enter any number.");
          let mut number = String::new();

          std::io::stdin()
              .read_line(&mut number)
              .expect("Failed to read line");

          let number: u32 = match number.trim().parse() {
              Ok(num) => num,
              Err(_) => continue,
          };

          let celcius = (number - 32) / (9 / 5);
          let fahrenheit = (celcius * (9 / 5)) + 32;

          println!("{number}°F -> {celcius}°C");
          println!("{number}°C -> {fahrenheit}°F");
          break;
      }
  }

  fn generate_nth_fibonacci_number() {
      loop {
          println!("Enter any number for n.");
          let mut number = String::new();

          std::io::stdin()
              .read_line(&mut number)
              .expect("Failed to read line");

          let number: u32 = match number.trim().parse() {
              Ok(num) => num,
              Err(_) => continue,
          };

          match number.cmp(&1) {
              std::cmp::Ordering::Less => println!("0"),
              std::cmp::Ordering::Equal => println!("1"),
              std::cmp::Ordering::Greater => {
                  println!("Fn = Fn-1 + Fn+2 for n>1");
                  println!("Example: 0,1,1,2,3,5,8,13,21");
              }
          }
          break;
      }
  }

  fn main() {
      // if_expressions();
      // handling_multiple_conditions_with_else_if();
      // using_if_in_a_let_statement();
      // repetition_with_loops();
      // returning_values_from_loops();
      // loop_labels_to_disambiguate_between_multiple_loops();
      // conditional_loops_with_while();
      // looping_through_a_collection_with_for();
      convert_temperature_between_fahrenheit_and_celcius();
      generate_nth_fibonacci_number();
  }
#+END_SRC

* Understanding Ownership
** What is Ownership?

      #+BEGIN_SRC rust
  fn variables_and_data_interacting_with_move() {
      // let x = 5;
      // let y = x;

      let s1 = String::from("hello");
      let s2 = s1.clone();

      println!("s1 = {s1}, s2 = {s2}");
      println!("{s1}, world!");
  }

  fn stack_only_data_copy() {
      let x = 5;
      let y = x;

      println!("x = {x}, y = {y}");
  }

  fn ownership_and_functions() {
      let s = String::from("hello"); // s comes into scope
      takes_ownership(s); // s's value moves into the function...
      // ... and so is no longer valid here
      let x = 5; // x comes into scope
      makes_copy(x); // Because i32 implements the Copy trait,
      // x does NOT move into the function,
      // so it's okay to use x afterward.
  } // Here, x goes out of scope, then s. However, because s's value was moved,
  // nothing special happens.

  fn takes_ownership(some_string: String) {
      // some_string comes into scope
      println!("{some_string}");
  } // Here, some_string goes out of scope and `drop` is called. The backing
  // memory is freed.

  fn makes_copy(some_integer: i32) {
      // some_integer comes into scope
      println!("{some_integer}")
  } // Here, some_integer goes out of scope. Nothing special happens.

  fn return_values_and_scope() {
      let s1 = gives_ownership(); // gives_ownership moves its return value into s1
      let s2 = String::from("hello"); // s2 comes into scope
      let s3 = takes_and_gives_back(s2); // s2 is moved into takes_and_gives_back, which also moves its return value into s3
  } // Here, s3 goes out of scope and is dropped. s2 ws moved, so nothing happens. s1 goes out of scope and is dropped.

  fn gives_ownership() -> String {
      // gives_ownership will move its return value into the function that calls it
      let some_string = String::from("yours"); //some_string comes into scope
      some_string // some_string is returned and moves out to the calling function
  }

  // This function takes a String and returns a String.
  fn takes_and_gives_back(a_string: String) -> String {
      // a_string comes into scope
      a_string // a_string is returned and moves out to the calling function
  }

  fn return_multiple_values_using_a_tuple() {
      let s1 = String::from("hello");
      let (s2, len) = calculate_length(s1);
      println!("The length of '{s2}' is {len}.")
  }

  fn calculate_length(s: String) -> (String, usize) {
      let length = s.len(); // len() returns the length of a String
      (s, length)
  }

  fn main() {
      // let s = "hello";
      // let mut s = String::from("hello");
      // s.push_str(", world!");
      // println!("{s}");
      // variables_and_data_interacting_with_move();
      return_values_and_scope();
      return_multiple_values_using_a_tuple();
  }
      #+END_SRC

** References and Borrowing

   BEGIN_SRC rust
    calculate_length(s: &String) -> usize {
     // s is a reference to a String
     s.len()
   // Here, s goes out of scope. But because s does not have ownership of what it refers to, the String is not dropped.

    fn borrowing_without_returning(){
      let s = String::from("hello");
      change(&s);
    }

    fn change(some_string: &String){
      some_string.push_str(", world");
    }

    mutable_references() {
     let mut s = String::from("hello");
     {
         let r1 = &mut s;
     } // r1 goes out of scope here, so we can make a new reference with no problems.
     let r2 = &mut s;

     let r1 = &s; // no problem
     let r2 = &s; // no problem
     // let r3 = &mut s; // BIG PROBLEM

     // println!("{r1}, {r2}, and {r3}");


    reference_scope() {
     let mut s = String::from("hello");
     let r1 = &s; // no problem
     let r2 = &s; // no problem
     println!("{r1} and {r2}");
     // Variables r1 and r2 will not be used after this point.

     let r3 = &mut s; // no problem
     println!("{r3}");


    dangling_references() {
     // let reference_to_string = dangle();
     let reference_to_string = no_dangle();


    fn dangle() -> &String { // dangle returns a reference to a String
      let s = String::from("hello"); // s is a new String
      &s // we return a reference to the String, s
    } // Here, s goes out of scope and is dropped, so its memory goes away.
    // Danger!

    no_dangle() -> String {
     let s = String::from("hello");
     s


    main() {
     let s1 = String::from("hello");
     let len = calculate_length(&s1);
     println!("The length of '{s1}' is {len}.");

     // borrowing_without_returning();
     mutable_references();
     reference_scope();

   END_SRC

** The Slice Type

#+BEGIN_SRC rust
  fn main() {
      let mut s = String::from("hello world");
      let word = first_word(&s);
      // s.clear(); // error
      println!("the first word is: {word}");

      let my_string = String::from("hello world");

      // `first_word` works on slices of `String`s, whether partial or whole.
      let word = first_word(&my_string[0..6]);
      let word = first_word(&my_string[..]);
      // `first_word` also works on references to `String`s, which are equivalent
      // to whole slices of `String`s
      let word = first_word(&my_string);

      let my_string_literal = "hello world";

      // `first_word` works on slices of string literals, whether partial or whole.
      let word = first_word(&my_string_literal[0..6]);
      let word = first_word(&my_string_literal[..]);

      // Because string literals *are* string slices already,
      // this works too, without the slice syntax!
      let word = first_word(my_string_literal);

      let a = [1, 2, 3, 4, 5];

      let slice = &a[1..3];
      assert_eq!(slice, &[2, 3]);
  }

  fn first_word(s: &str) -> &str {
      let bytes = s.as_bytes();

      for (i, &item) in bytes.iter().enumerate() {
          if item == b' ' {
              return &s[0..i];
          }
      }

      &s[..]
  }
#+END_SRC

* Using Structs to Structure Related Data
** Defining and Instantiating Structs

#+BEGIN_SRC rust
struct User {
    active: bool,
    username: String,
    email: String,
    sign_in_count: u64,
}

fn build_user(email: String, username: String) -> User {
    User {
        active: true,
        username,
        email,
        sign_in_count: 1,
    }
}

fn creating_different_types_with_tuple_structs() {
    struct Color(i32, i32, i32);
    struct Point(i32, i32, i32);

    let black = Color(0, 0, 0);
    let origin = Point(0, 0, 0);
}

fn defining_unit_like_structs() {
    struct AlwaysEqual;

    let subject = AlwaysEqual;
}

fn main() {
    let mut user1 = User {
        active: true,
        username: String::from("someusername123"),
        email: String::from("someone@example.com"),
        sign_in_count: 1,
    };

    user1.email = String::from("anotheremail@example.com");

    // let user2 = User {
    //   active: user1.active,
    //   username: user1.username,
    //   email: String::from("another@example.com"),
    //   sign_in_count: user1.sign_in_count,
    // };

    let user2 = User {
        email: String::from("another@example.com"),
        ..user1
    };

    creating_different_types_with_tuple_structs();
    defining_unit_like_structs();
}
#+END_SRC

** An Example Program Using Structs

#+BEGIN_SRC rust
fn area(width: u32, height: u32) -> u32 {
    width * height
}

fn refactoring_with_tuples() {
    fn area(dimensions: (u32, u32)) -> u32 {
        dimensions.0 * dimensions.1
    }

    let rect1 = (30, 50);

    println!(
        "The area of the rectangle is {} square pixels.",
        area(rect1)
    )
}

fn refactoring_with_structs() {
    struct Rectangle {
        width: u32,
        height: u32,
    }

    fn area(rectangle: &Rectangle) -> u32 {
        rectangle.width * rectangle.height
    }

    let rect1 = Rectangle {
        width: 30,
        height: 50,
    };

    println!(
        "The area of the rectangle is {} square pixels.",
        area(&rect1)
    )
}

fn adding_functionality_with_derived_traits() {
    #[derive(Debug)]
    struct Rectangle {
        width: u32,
        height: u32,
    }

    let rect1 = Rectangle {
        width: 30,
        height: 50,
    };

    println!("rect1 is {rect1:?}");
    println!("rect1 is {rect1:#?}");

    let scale = 2;
    let rect1 = Rectangle {
        width: dbg!(30 * scale),
        height: 50,
    };

    dbg!(&rect1);
}

fn main() {
    let width1 = 30;
    let height1 = 50;

    println!(
        "The area of the rectangle is {} square pixels.",
        area(width1, height1)
    );

    refactoring_with_tuples();
    refactoring_with_structs();
    adding_functionality_with_derived_traits();
}
#+END_SRC

** Methods

#+BEGIN_SRC rust
#+END_SRC

* Enums and Pattern Matching
** Defining an Enum
** The match Control Flow Construct
** Concise Control Flow with if let and let...else
* Packages, Crates, and Modules
** Packages and Crates
** Control Scope and Privacy with Modules
** Paths for Referring to an Item in the Module Tree
** Bringing Paths Into Scope with the use Keyword
** Separating Modules into Different Files
* Common Collections
** Storing Lists of Values with Vectors
** Storing UTF-8 Encoded Text with Strings
** Storing Keys with Associated Values in Hash Maps
* Error Handling
** Unrecoverable Errors with panic!
** Recoverable Errors with Result
** To panic! or Not to panic!
* Generic Types, Traits, and Lifetimes
** Generic Data Types
** Defining Shared Behavior with Traits
** Validating References with Lifetimes
* Writing Automated Tests
** How to Write Tests
** Controlling How Tests Are Run
** Test Organization
* An I/O Project: Building a Command Line Program
** Accepting Command Line Arguments
** Reading a File
** Refactoring to Improve Modularity and Error Handling
** Adding Functionality with Test Driven Development
** Working with Environment Variables
** Redirecting Errors to Standard Error
* Functional Language Features: Iterators and Closures
** Closures
** Processing a Series of Items with Iterators
** Improving Our I/O Project
** Performance in Loops vs. Iterators
* More about Cargo and Crates.io
** Customizing Builds with Release Profiles
** Publishing a Crate to Crates.io
** Cargo Workspaces
** Installing Binaries with cargo install
** Extending Cargo with Custom Commands
* Smart Pointers
** Using Box<T> to Point to Data on the Heap
** Treating Smart Pointers Like Regular References
** Running Code on Cleanup with the Drop Trait
** Rc<T>, the Reference Counted Smart Pointer
** RefCell<T> and the Interior Mutability Pattern
** Reference Cycles Can Leak Memory
* Fearless Concurrency
** Using Threads to Run Code Simultaneously
** Transfer Data Between Threads with Message Passing
** Shared-State Concurrency
** Extensible Concurrency with Send and Sync
* Fundamentals of Asynchronous Programming: Async, Await, Futures, and Streams
** Futures and the Async Syntax
** Applying Concurrency with Async
** Working With Any Number of Futures
** Streams: Futures in Sequence
** A Closer Look at the Traits for Async
** Futures, Tasks, and Threads
* Object Oriented Programming Features
** Characteristics of Object-Oriented Languages
** Using Trait Objects to Abstract over Shared Behavior
** Implementing an Object-Oriented Design Pattern
* Patterns and Matching
** All the Places Patterns Can Be Used
** Refutability: Whether a Pattern Might Fail to Match
** Pattern Syntax
* Advanced Features
** Unsafe Rust
** Advanced Traits
** Advanced Types
** Advanced Functions and Closures
** Macros
* Final Project: Building a Multithreaded Web Server
** Building a Single-Threaded Web Server
** From Single-Threaded to Multithreaded Server
** Graceful Shutdown and Cleanup
* Appendix
** A - Keywords
** B - Operators and Symbols
** C - Derivable Traits
** D - Useful Development Tools
** E - Editions
** F - Translations of the Book
** G - How Rust is Made and “Nightly Rust”
