CONFIG_WOLFSSL=y
CONFIG_WOLFSSL_BUILTIN=y
CONFIG_WOLFSSL_SETTINGS_FILE="wolfssl_user_settings.h"

CONFIG_WOLFSSH=y
CONFIG_WOLFSSH_SETTINGS_FILE="wolfssh_user_settings.h"

# wolfSSL's wc_port.h requires POSIX threads when SINGLE_THREADED is not set.
CONFIG_POSIX_API=y
CONFIG_POSIX_THREADS=y
