serial_number: robot-0004
version: 1
system:
  namespace: robot4
  hosts:
    - hostname: rpi5-16
      ip: 10.81.190.24
      board: rpi_5
platform:
  attachments: []
  drivetrain:
    model: pwm_dir
    pwm_frequency_hz: 20000.0
    max_linear_velocity_mps: 2.0
    left:
      pwm_pin: 32 # PWM1 input
      dir_pin: 36 # DIR1 input
      forward_level: true
    right:
      pwm_pin: 33 # PWM2 input
      dir_pin: 37 # DIR2 input
      forward_level: false
sensors:
  camera:
    - model: oak_d_sr
      parent: base_link
      xyz: [0.575, 0.5, 0.31]
      rpy: [0.0, 0.0, 0.0]
      ros_parameters:
        camera_0: {}
