pub const RAIL_CROSS_WIDTH_MM: f64 = 50.8;
pub const RAIL_CROSS_HEIGHT_MM: f64 = 25.4;
pub const RAIL_WALL_THICKNESS_MM: f64 = 3.175;
pub const RAIL_HOLE_DIAMETER_MM: f64 = 5.0;
pub const RAIL_HOLE_SPACING_MM: f64 = 12.7;
pub const RAIL_FILLET_RADIUS_MM: f64 = 0.5;

pub const GUSSET_ARM_LENGTH_MM: f64 = 57.15;
pub const GUSSET_ARM_WIDTH_MM: f64 = 25.4;
pub const GUSSET_THICKNESS_MM: f64 = 3.175;
pub const GUSSET_HOLE_DIAMETER_MM: f64 = 4.9784;
pub const GUSSET_HOLE_PITCH_MM: f64 = 12.7;
pub const GUSSET_HOLES_PER_ARM: usize = 5;

pub const RAIL_END_CAP_FLANGE_THICKNESS_MM: f64 = 4.0;
pub const RAIL_END_CAP_BOSS_DEPTH_MM: f64 = 7.0;
pub const RAIL_END_CAP_BOSS_WALL_MM: f64 = 3.0;

pub const POST_HEIGHT_MM: f64 = 303.8;
pub const POST_INSET_FROM_END_MM: f64 = 152.407;
pub const POST_LENGTHWISE_BAR_DROP_FROM_TOP_MM: f64 = 83.15;

pub const CASTER_MOUNT_BAR_LENGTH_MM: f64 = 177.8;
pub const CASTER_MOUNT_BAR_WIDTH_MM: f64 = 25.4;
pub const CASTER_MOUNT_BAR_GAP_MM: f64 = 19.05;
pub const CASTER_MOUNT_BAR_PITCH_MM: f64 = CASTER_MOUNT_BAR_WIDTH_MM + CASTER_MOUNT_BAR_GAP_MM;

pub const WHEEL_HUB_CLEARANCE_FROM_MOTOR_FACE_MM: f64 = 5.0;
