"""
Microvisor Test Runner

Auto-discovers namespaced test() functions and legacy *_run_tests()
functions in src/ and generates a Unity test harness.
Renders screenplay-style output with trace narration.
"""

import os
import re

import click
from platformio.test.runners.unity import UnityTestRunner

ANSI_RE = re.compile(r"\x1b\[[0-9;]*m")
NAMESPACED_TEST_RE = re.compile(r"void\s+([\w:]+::test)\s*\(\s*(?:void)?\s*\)")
LEGACY_TEST_RE = re.compile(r"void\s+(\w+_run_tests)\s*\(\s*(?:void)?\s*\)")


class CustomTestRunner(UnityTestRunner):

    def stage_building(self):
        self._generate_harness()
        super().stage_building()

    def on_testing_line_output(self, line):
        if self.options.verbose:
            click.echo(line, nl=False)
            return

        line = ANSI_RE.sub("", line or "").strip()
        if not line:
            return

        test_case = self.parse_test_case(line)
        if test_case:
            self.test_suite.add_case(test_case)
            status = click.style(
                "[%s]" % test_case.status.name,
                fg=test_case.status.to_ansi_color(),
            )
            click.echo("%s %s" % (status, test_case.name.replace("_", " ")))
        elif ":INFO:" in line:
            msg = line.split(":INFO:", 1)[-1].strip()
            click.echo("  %s %s" % (
                click.style("·", fg="cyan"),
                click.style(msg, fg="cyan", dim=True),
            ))

        if all(s in line for s in ("Tests", "Failures", "Ignored")):
            self.test_suite.on_finish()

    # -- Harness generation -------------------------------------------------

    def _generate_harness(self):
        src_dir = self.project_config.get("platformio", "src_dir")
        tests_dir = self.project_config.get("platformio", "test_dir")
        harness_dir = os.path.join(tests_dir, "test_unit")
        harness_path = os.path.join(harness_dir, "main.cpp")
        os.makedirs(harness_dir, exist_ok=True)

        runners = sorted(self._discover_runners(src_dir))
        if not runners:
            return

        content = self._render_harness(runners)
        if os.path.exists(harness_path):
            with open(harness_path, "r") as f:
                if f.read() == content:
                    return

        with open(harness_path, "w") as f:
            f.write(content)

    @staticmethod
    def _discover_runners(src_dir):
        runners = []
        for root, _, files in os.walk(src_dir):
            for name in files:
                if not name.endswith((".cpp", ".c")):
                    continue
                with open(os.path.join(root, name), "r") as f:
                    text = f.read()
                    for match in NAMESPACED_TEST_RE.finditer(text):
                        runners.append(match.group(1))
                    for match in LEGACY_TEST_RE.finditer(text):
                        runners.append(match.group(1))
        return runners

    @staticmethod
    def _render_harness(runners):
        decls = []
        calls = []
        for r in runners:
            if "::" in r:
                ns, fn = r.rsplit("::", 1)
                decls.append("namespace %s { void %s(); }" % (ns, fn))
            else:
                decls.append("void %s(void);" % r)
            calls.append("  %s();" % r)
        return (
            "// Auto-generated by test_custom_runner.py — do not edit\n"
            "#include <Arduino.h>\n"
            "#include <unity.h>\n"
            "\n"
            "%s\n"
            "\n"
            "void setUp(void) {}\n"
            "void tearDown(void) {}\n"
            "\n"
            "void setup(void) {\n"
            "  delay(2000);\n"
            "  UNITY_BEGIN();\n"
            "%s\n"
            "  UNITY_END();\n"
            "}\n"
            "\n"
            "void loop(void) { delay(1000); }\n"
        ) % ("\n".join(decls), "\n".join(calls))
