use alloc::string::String as AllocString;
use core::fmt::Write;

use crate::{
    config::{app, board},
    filesystems::sd,
    services::{identity, system},
};

pub fn initialize_layout() {
    let _ = sd::create_directory("ETC");
    let _ = sd::create_directory("BOOT");
    let _ = sd::create_directory("TMP");

    identity::ensure_home_hierarchy();
    generate_rc_conf();
    generate_loader_conf();
}

pub fn generate_rc_conf() {
    let mut rc = AllocString::new();
    let _ = write!(rc, "# /etc/rc.conf -- generated by Microvisor\r\n");
    let _ = write!(
        rc,
        "# Do not edit. Configuration is compiled into firmware.\r\n\r\n"
    );
    let _ = write!(rc, "hostname=\"{}\"\r\n", app::HOSTNAME);
    let _ = write!(rc, "sshd_enable=\"YES\"\r\n");
    let _ = write!(rc, "sshd_port=\"{}\"\r\n", app::ssh::PORT);
    let _ = write!(rc, "sntpd_enable=\"YES\"\r\n");
    let _ = write!(rc, "sntpd_server=\"{}\"\r\n", app::NTP_SERVER);
    let _ = write!(rc, "httpd_enable=\"YES\"\r\n");
    let _ = write!(rc, "httpd_port=\"{}\"\r\n", app::http::PORT);
    let _ = write!(rc, "otad_enable=\"YES\"\r\n");
    let _ = write!(rc, "otad_port=\"{}\"\r\n", app::ota::PORT);
    let _ = write!(rc, "wifi_ap_ssid=\"{}\"\r\n", app::wifi::ap::SSID);
    let _ = write!(rc, "wifi_ap_auth=\"{}\"\r\n", app::wifi::ap::AUTH_MODE);
    let _ = write!(rc, "timezone=\"{}\"\r\n", app::time::ZONE);
    let _ = sd::write_file_at("/etc", "RC.CONF", rc.as_bytes());
}

pub fn generate_loader_conf() {
    let mut loader = AllocString::new();
    let _ = write!(loader, "# /boot/loader.conf -- generated by Microvisor\r\n");
    let _ = write!(
        loader,
        "# Do not edit. Hardware config is compiled into firmware.\r\n\r\n"
    );
    let _ = write!(loader, "fatfs_load=\"YES\"\r\n");
    let _ = write!(loader, "sd_spi_bus=\"{}\"\r\n", app::sd_card::DEVICE);
    let _ = write!(
        loader,
        "i2c_frequency=\"{}\"\r\n",
        board::i2c::FREQUENCY_KHZ
    );
    let _ = write!(
        loader,
        "sensor_power_gpio=\"{}\"\r\n",
        board::i2c::LEGACY_POWER_GPIO
    );
    let snapshot = system::snapshot();
    let _ = write!(loader, "heap_size=\"{}\"\r\n", snapshot.heap_total);
    let _ = sd::write_file_at("/boot", "LOADER.CO", loader.as_bytes());
}
