{
  imports = [
    ./doom
    ./bash.nix
    ./bat.nix
    ./btop.nix
    ./chromium.nix
    ./direnv.nix
    ./eza.nix
    ./fastfetch.nix
    ./fd.nix
    ./fzf.nix
    ./gh.nix
    ./git.nix
    ./go.nix
    ./gpg.nix
    ./home-manager.nix
    ./hyprland.nix
    ./jq.nix
    ./jqp.nix
    ./k9s.nix
    ./kitty.nix
    ./kubecolor.nix
    ./lazydocker.nix
    ./lazygit.nix
    ./lazysql.nix
    ./less.nix
    ./mu.nix
    ./neovim.nix
    ./nh.nix
    ./nix-index.nix
    ./pandoc.nix
    ./ripgrep.nix
    ./sftpman.nix
    ./starship
    ./television.nix
    ./texlive.nix
    ./tex-fmt.nix
    ./tmux.nix
    ./vscode.nix
    ./yazi.nix
    ./zed.nix
    ./zellij.nix
    ./zoxide.nix
    ./zsh.nix
    ./obs-studio.nix
    ./vivaldi.nix
    ./sketchybar.nix
  ];
}
