CREATE TABLE resources(
    id UUID PRIMARY KEY DEFAULT generate_uuid_v7(),
    name TEXT NOT NULL,
    stack_id UUID NOT NULL REFERENCES stacks(id),
    urn TEXT NOT NULL UNIQUE,
    type TEXT NOT NULL,
    package TEXT NOT NULL,
    module TEXT NOT NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    modified_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);
