/* Autogenerated file. Do not edit manually. */

/* eslint-disable max-classes-per-file */
/* eslint-disable @typescript-eslint/no-unused-vars */
/* eslint-disable @typescript-eslint/consistent-type-imports */

/*
  Fuels version: 0.100.3
  Forc version: 0.67.0
  Fuel-Core version: 0.41.9
*/

import {
  Account,
  BigNumberish,
  BN,
  decompressBytecode,
  Script as __Script,
} from 'fuels';

export type TestScriptInputs = [input: BigNumberish];
export type TestScriptOutput = BN;

const abi = {
  "programType": "script",
  "specVersion": "1",
  "encodingVersion": "1",
  "concreteTypes": [
    {
      "type": "u64",
      "concreteTypeId": "1506e6f44c1d6291cdf46395a8e573276a4fa79e8ace3fc891e092ef32d1b0a0"
    }
  ],
  "metadataTypes": [],
  "functions": [
    {
      "inputs": [
        {
          "name": "input",
          "concreteTypeId": "1506e6f44c1d6291cdf46395a8e573276a4fa79e8ace3fc891e092ef32d1b0a0"
        }
      ],
      "name": "main",
      "output": "1506e6f44c1d6291cdf46395a8e573276a4fa79e8ace3fc891e092ef32d1b0a0",
      "attributes": null
    }
  ],
  "loggedTypes": [],
  "messagesTypes": [],
  "configurables": []
};

const bytecode = decompressBytecode('H4sIAAAAAAAAAzVRPU/jQBB9yVk665rbOwKKli8XgCgjQcFHwVp25JgEsRKKoLFsOsrIQogyPwEKPkpKynVHmZKSktItEpZokIIowjMJ28y8NzNvPla+NXAKWPh+VfFjo9GgIkYjyFeNS2J9mOljhT9xgR1ai3ZTe9lQB6aXNGHTTxJX2DrInksceWY7cgHmuaWf+rBn/ZoSrqXIbZNzWXtO/y9rTya1P1pPJWbOlnwBnOEajj7zqv7MLc7akd5TqasYV6lvYcUHpN+DbpvbuBBTJUdbi18xnRROnX0ek8DUdTs7T0JBnDlJk3zb1MfY9EscHRgR7Zt/UWD+py3YIqz1p8OlwVkLFfb9Ta46G6730w5je0uDlQ6wOu8rqXsQoa/iEEgVY24N1MzjQs3FRWOesy5ozzS4U9nb5o517ngxwfkE5/Q3xr5pjWPGlJh7zuimEJx3SK1F7Tr29708w5s7gnX3zBPUeCAvki5E5OpK1NVY7gJXwK9rmzfiX0rvDjLIId+JPwRuyd8wvjsEAv78F4ALhw8QAgAA');

export class TestScript extends __Script<TestScriptInputs, TestScriptOutput> {

  static readonly abi = abi;
  static readonly bytecode = bytecode;

  constructor(wallet: Account) {
    super(bytecode, abi, wallet);
  }
}
