#!/usr/bin/env python3
"""
Generate a Zephyr ZTEST C bridge from a zephyr-lang-zig zig_tests.zig file.

For every `export fn zig_test_NAME(...)` found in the Zig source, emit:
    void zig_test_NAME(void);
    ZTEST(<suite>, test_NAME) { zig_test_NAME(); }

If the file additionally exports `zig_before()` or `zig_after()`, wire
those as the suite's per-test before/after hooks. The Zig source then
expresses lifecycle setup once instead of repeated at the top of every
test function.
"""
import argparse
import re
import sys


def main():
    parser = argparse.ArgumentParser()
    parser.add_argument("--zig-source", required=True)
    parser.add_argument("--suite", required=True)
    parser.add_argument("--output", required=True)
    args = parser.parse_args()

    with open(args.zig_source) as f:
        code = f.read()

    test_pattern = re.compile(r"^export fn (zig_test_\w+)\s*\(", re.MULTILINE)
    names = test_pattern.findall(code)

    if not names:
        print(
            f"gen_test_main: no `export fn zig_test_*` found in {args.zig_source}",
            file=sys.stderr,
        )
        sys.exit(1)

    has_before = bool(re.search(r"^export fn zig_before\s*\(\s*\)", code, re.MULTILINE))
    has_after = bool(re.search(r"^export fn zig_after\s*\(\s*\)", code, re.MULTILINE))

    lines = [
        f"/* Auto-generated by gen_test_main.py from {args.zig_source}. */\n",
        "#include <stdint.h>\n",
        "#include <stddef.h>\n",
        "#include <stdbool.h>\n",
        "#include <zephyr/sys/printk.h>\n",
        "#include <zephyr/ztest.h>\n",
        "\n",
    ]

    for name in names:
        lines.append(f"void {name}(void);\n")
    if has_before:
        lines.append("void zig_before(void);\n")
    if has_after:
        lines.append("void zig_after(void);\n")
    lines.append("\n")

    if has_before:
        lines.append(
            "static void zig_before_each(void *unused) { ARG_UNUSED(unused); zig_before(); }\n"
        )
    if has_after:
        lines.append(
            "static void zig_after_each(void *unused) { ARG_UNUSED(unused); zig_after(); }\n"
        )
    if has_before or has_after:
        lines.append("\n")

    before_arg = "zig_before_each" if has_before else "NULL"
    after_arg = "zig_after_each" if has_after else "NULL"

    lines.append(
        f"ZTEST_SUITE({args.suite}, NULL, NULL, {before_arg}, {after_arg}, NULL);\n"
    )
    lines.append("\n")

    for name in names:
        case = "test_" + name[len("zig_test_") :]
        lines.append(f"ZTEST({args.suite}, {case})\n")
        lines.append("{\n")
        lines.append(f"\t{name}();\n")
        lines.append(f"\tprintk(\"PASS - {case} in 0.000 seconds\\n\");\n")
        lines.append("}\n")
        lines.append("\n")

    with open(args.output, "w") as f:
        f.writelines(lines)


if __name__ == "__main__":
    main()
