#+title: Key Details

Greetings Team!

I hope you guys are doing well.


Please read this email in its entirety as it contains information pertaining to your team.


Wave: 4 

Team 1: Jayden, Carla, Khyatis and Jorge

Team 4: Maria José, Julie Anne, Syna and Karene

Team 3: Ansh,Shrikar, Mumtahin and Rayhaan


Your arrival time will be: 9:45am SHARP


We will be waiting for you at the cloud deck on the 3rd floor of JMSB, where we will give you a brief summary of the event and take you to your case solving rooms.


Under no circumstances is the case solving time to be modified, please arrive on time as no extra time will be given if you arrive late.


The Detailed Schedule for the event  and the Academic Rules and Regulations document is attached to this email. Please make sure to look it over. 

Once you arrive at school, please arrive at the JMSB Lobby at your wave's arrival time. There will be executive members present to lead you to the ENGCOMM/Registration Booth. 

About 5 min before the Submission time, one of our executive members will notify you and pick you up to bring you to your presentation room. Please leave the Study room clean and organized as it was when you came in. 

If at any time during the case solving period you have questions or are unsure about something, executive members will be present to support you. Note that you are not allowed to leave the study room during the case solving - notify the executive team members if anything comes up.

The Academic Rules and Regulations document has been attached to this document. You are expected to read them in detail before the competition.  

Divisions are competing against each other to become finalists (you will know in which division you are once you arrive). At the final announcements, we will jump right into the presentation of the first division. There will be no prep-time given and we will be going from one presentation to another back to back. Therefore you must stay for the final presentations, because if your team wins, you will be required to present again and if you are not around you will automatically be disqualified..

Dress Code: All participants are expected to be in business formal attire.

Please note that participants are responsible for bringing their own technology - laptop, mouse, tablets, etc. ENGCOMM will not be providing any supporting equipment.

REMINDER 1: Additionally, our Marketing team would love to feature your participation in this year’s ENGCOMM x MTL! If you’d like to take part, please send us a professional headshot. We’ll be creating a special template celebrating your team, which you’re welcome to share on your social media. Feel free to tag us @engcommofficial we’d love to see it!

REMINDER 2: to send us your updated academic Transcript and CV if not already done.

REMINDER 3: to send  us your team name no later than Friday 9:00 PM.

Please confirm that you received this email .

If you have any questions or concerns feel free to reach out to partnerships@engcomm.ca . 


Warm regards,


Sandra Assumani | Director of Partnerships 2024

Engineering & Commerce Case Competition (ENGCOMM)

1455 Maisonneuve Boulevard West, Suite H860-4, Montreal, QC, H3G 1M8 

Cell: 514 823-1881

Email: partnerships.director@engcomm.ca 

Website: engcomm.ca | Facebook | LinkedIn
