;; -*- mode: eask; lexical-binding: t -*-

(package "loco-rs"
         "0.0.1"
         "loco-rs (cargo loco) project integration for GNU Emacs")

(website-url "https://github.com/MFarabi619/MFarabi619/modules/home/programs/emacs/extra/loco-rs")
(keywords "tools" "languages")

(package-file "loco-rs.el")

(script "check" "eask lint checkdoc && eask compile && eask clean elc && eask test buttercup")

(development
 (depends-on "buttercup"))
