CONFIG_DNS_RESOLVER=y
CONFIG_DNS_RESOLVER_CACHE=y
CONFIG_DNS_RESOLVER_MAX_SERVERS=3
CONFIG_DNS_RESOLVER_AI_MAX_ENTRIES=8
CONFIG_DNS_RESOLVER_MAX_NAME_LEN=128
CONFIG_DNS_RESOLVER_MAX_ANSWER_SIZE=2048
CONFIG_DNS_RESOLVER_CACHE_MAX_ENTRIES=128

CONFIG_DNS_NUM_CONCUR_QUERIES=32
