CONFIG_NET_HOSTNAME="xiao"
CONFIG_WIFI_USAGE_MODE_STA_AP=y

CONFIG_SPIRAM_MODE_OCT=y
CONFIG_ESPTOOLPY_OCT_FLASH=n
CONFIG_ESPTOOLPY_FLASHSIZE_8MB=y
CONFIG_ESPTOOLPY_FLASHFREQ_40M=y
CONFIG_ESPTOOLPY_FLASHMODE_QIO=y
CONFIG_ESP_SPIRAM_HEAP_SIZE=6291456
