CONFIG_SDMMC_STACK=y
CONFIG_FS_FATFS_EXFAT=y

CONFIG_SPIRAM_MODE_OCT=y
CONFIG_ESPTOOLPY_OCT_FLASH=n
CONFIG_NET_HOSTNAME="xiao-sense"
CONFIG_WIFI_USAGE_MODE_STA_AP=y
CONFIG_ESPTOOLPY_FLASHSIZE_8MB=y
# OCT PSRAM + mcumgr OTA WREN bug: flash must stay at 40M DIO
CONFIG_ESPTOOLPY_FLASHFREQ_40M=y
CONFIG_ESPTOOLPY_FLASHMODE_DIO=y
CONFIG_ESP_SPIRAM_HEAP_SIZE=6291456
