CONFIG_SPIRAM_MODE_OCT=y
CONFIG_NET_HOSTNAME="xiao"
CONFIG_WIFI_USAGE_MODE_STA_AP=y
CONFIG_ESPTOOLPY_FLASHSIZE_8MB=y
CONFIG_ESP_SPIRAM_HEAP_SIZE=6291456

# OCT PSRAM + mcumgr OTA WREN bug: flash must stay at 40M DIO
CONFIG_ESPTOOLPY_FLASHFREQ_40M=y
CONFIG_ESPTOOLPY_FLASHMODE_DIO=y
