CONFIG_NET_HOSTNAME="xiao-sense"
CONFIG_WIFI_USAGE_MODE_STA_AP=y

CONFIG_SPIRAM_MODE_OCT=y
CONFIG_ESPTOOLPY_OCT_FLASH=n
CONFIG_ESPTOOLPY_FLASHSIZE_8MB=y
CONFIG_ESPTOOLPY_FLASHFREQ_40M=y
CONFIG_ESPTOOLPY_FLASHMODE_QIO=y
CONFIG_ESP_SPIRAM_HEAP_SIZE=6291456

CONFIG_SDMMC_STACK=y
CONFIG_FS_FATFS_EXFAT=y
