# [[file:../CONTRIBUTING.org::*\[\[https:/github.com/jorgerojas26/lazysql\]\[lazysql\]\]][[[https://github.com/jorgerojas26/lazysql][lazysql]]:1]]
[application]
TreeWidth            = 20
DefaultPageSize      = 300
EnterOpensJSONViewer = true
DisableSidebar       = false
SidebarOverlay       = false
JSONViewerWordWrap   = false
MaxQueryHistoryPerConnection = 100

[[database]]
ReadOnly  = false
Provider  = 'postgres'
Name      = 'microvisor'
Schemas   = [ 'public' ]
URL       = 'postgresql://mfarabi@${env:PGHOST}/microvisor?sslmode=disable'
# [[https://github.com/jorgerojas26/lazysql][lazysql]]:1 ends here
