// Auto-generated by test_custom_runner.py — do not edit
#include <Arduino.h>
#include <unity.h>

namespace filesystems::eeprom { void test(); }
namespace filesystems::littlefs { void test(); }
namespace filesystems::sd { void test(); }
namespace hardware::i2c { void test(); }
namespace hardware::system { void test(); }
namespace networking::ble { void test(); }
namespace networking::ota { void test(); }
namespace networking::provisioning { void test(); }
namespace networking::sntp { void test(); }
namespace networking::telnet { void test(); }
namespace networking::update { void test(); }
namespace networking::wifi { void test(); }
namespace programs::shell { void test(); }
namespace sensors::carbon_dioxide { void test(); }
namespace sensors::temperature_and_humidity { void test(); }
namespace sensors::voltage { void test(); }
namespace services::cloudevents { void test(); }
namespace services::email { void test(); }
namespace services::http { void test(); }
namespace services::http_e2e { void test(); }
namespace services::rtc { void test(); }
namespace services::sshd { void test(); }

void setUp(void) {}
void tearDown(void) {}

void setup(void) {
  delay(2000);
  UNITY_BEGIN();
  filesystems::eeprom::test();
  filesystems::littlefs::test();
  filesystems::sd::test();
  hardware::i2c::test();
  hardware::system::test();
  networking::ble::test();
  networking::ota::test();
  networking::provisioning::test();
  networking::sntp::test();
  networking::telnet::test();
  networking::update::test();
  networking::wifi::test();
  programs::shell::test();
  sensors::carbon_dioxide::test();
  sensors::temperature_and_humidity::test();
  sensors::voltage::test();
  services::cloudevents::test();
  services::email::test();
  services::http::test();
  services::http_e2e::test();
  services::rtc::test();
  services::sshd::test();
  UNITY_END();
}

void loop(void) { delay(1000); }
