default_config:

homeassistant:
  name: Apidae Systems
  unit_system: metric
  time_zone: America/Toronto

mqtt:
  broker: mosquitto
  port: 1883
  discovery: true
  discovery_prefix: homeassistant

recorder:
  auto_purge: true
  purge_keep_days: 10

history:
