/*
 * Copyright (c) 2026 Apidae Systems
 *
 * SPDX-License-Identifier: Apache-2.0
 */

#ifndef CERATINA_SENSORS_CHANNELS_H_
#define CERATINA_SENSORS_CHANNELS_H_

#include <zephyr/drivers/sensor.h>

enum sensor_channel_ceratina {
	SENSOR_CHAN_CERATINA_WIND_SPEED = SENSOR_CHAN_PRIV_START,
	SENSOR_CHAN_CERATINA_WIND_DIRECTION_DEGREES,
	SENSOR_CHAN_CERATINA_WIND_DIRECTION_SLICE,
	SENSOR_CHAN_CERATINA_RAINFALL,
	SENSOR_CHAN_CERATINA_SOIL_MOISTURE,
	SENSOR_CHAN_CERATINA_SOIL_CONDUCTIVITY,
	SENSOR_CHAN_CERATINA_SOIL_SALINITY,
	SENSOR_CHAN_CERATINA_SOIL_TDS,
	SENSOR_CHAN_CERATINA_SOIL_PH,
};

enum sensor_attribute_ceratina {
	SENSOR_ATTR_CERATINA_CLEAR = SENSOR_ATTR_PRIV_START,
	SENSOR_ATTR_CERATINA_SCAN,
	SENSOR_ATTR_CERATINA_SLAVE_ID,
};

#endif /* CERATINA_SENSORS_CHANNELS_H_ */
