;; -*- mode: eask; lexical-binding: t -*-

(package "pixi"
         "0.0.1"
         "Pixi workspace integration")

(website-url "https://github.com/MFarabi619/MFarabi619/modules/home/programs/emacs/extra/pixi")
(keywords "tools" "embedded")

(package-file "pixi.el")

(script "check" "eask lint checkdoc && eask compile && eask clean elc && eask test buttercup")

(development
 (depends-on "buttercup"))
