CONFIG_NET_LOG=y
CONFIG_NET_SHELL=y
CONFIG_NETWORKING=y
CONFIG_NET_NATIVE=y
CONFIG_NET_MAX_CONN=16
CONFIG_NET_CONNECTION_MANAGER=y
CONFIG_NET_TC_THREAD_COOPERATIVE=y

CONFIG_NET_MGMT=y
CONFIG_NET_MGMT_EVENT=y
CONFIG_NET_MGMT_EVENT_INFO=y
CONFIG_NET_MGMT_EVENT_QUEUE_SIZE=10
CONFIG_NET_MGMT_EVENT_STACK_SIZE=4096
