CONFIG_SNTP=y
CONFIG_DATE_SHELL=y

CONFIG_NET_CONFIG_SETTINGS=y
CONFIG_NET_CONFIG_AUTO_INIT=n
CONFIG_NET_CONFIG_CLOCK_SNTP_INIT=y
CONFIG_NET_CONFIG_SNTP_INIT_RESYNC=y
CONFIG_NET_CONFIG_SNTP_INIT_SERVER="pool.ntp.org"
CONFIG_NET_CONFIG_SNTP_INIT_USE_CONNECTION_MANAGER=y
