[build]
base = "workspace/apps/web"
publish = "dist"
command = "rustup toolchain install stable; cargo install --locked trunk; trunk build"

[context.production]
environment = { NETLIFY_EXPERIMENTAL_BUILD_RUST_SOURCE = "true" }
