CONFIG_FILE_SYSTEM=y
CONFIG_FILE_SYSTEM_MKFS=y
# CONFIG_FS_LOG_LEVEL_WRN=y
CONFIG_FS_LOG_LEVEL_DBG=y
CONFIG_FILE_SYSTEM_SHELL=y

CONFIG_FS_FATFS_LFN=y
CONFIG_FS_FATFS_HAS_RTC=y
CONFIG_FS_FATFS_EXTRA_NATIVE_API=y

CONFIG_FAT_FILESYSTEM_ELM=y

CONFIG_MCUMGR_GRP_FS=y
CONFIG_MCUMGR_GRP_FS_MAX_FILE_SIZE_4GB=y
CONFIG_MCUMGR_GRP_FS_FILE_STATUS=y
CONFIG_MCUMGR_GRP_FS_CHECKSUM_HASH=y
CONFIG_MCUMGR_GRP_FS_HASH_SHA256=y
CONFIG_MCUMGR_GRP_FS_CHECKSUM_IEEE_CRC32=y
