[alias]
# =========== cargo +stable ============= #

simulator = [
  "run", "--release",
  "--package", "simulator",
]

stm32 = [
  "run", "--release",
  "--target", "thumbv7em-none-eabihf"
  ]

stm32h723zg = [ "stm32", "--bin", "h723zg" ]

# ======================================= #

esp   = [
  "run", "--release",
  "--package", "firmware",
  "--config", "unstable.build-std=[\"core\",\"alloc\"]"
  ]

esp32   = [
  "esp",
  "--target", "xtensa-esp32-none-elf"
  ]

esp32s3 = [
  "esp",
  "--target", "xtensa-esp32s3-none-elf"
  ]

test-esp = [
  "test",
  "--package", "firmware",
  "--target", "xtensa-esp32s3-none-elf",
  "--config", "unstable.build-std=[\"core\",\"alloc\"]"
]


[target.thumbv7em-none-eabihf]
runner    = "probe-rs run --chip stm32h723zg"

[target.xtensa-esp32s3-none-elf]
runner    = "probe-rs run --chip esp32s3"

[target.xtensa-esp32-none-elf]
runner    = "espflash flash --monitor --chip esp32"

[env]
DEFMT_LOG = "info"
