[package]
name = "robot_description"
version = "0.1.0"
edition = "2021"
default-run = "assembly"

[features]
generator = ["dep:cadrum", "dep:comfy-table", "dep:serde", "dep:serde_yaml"]

[dependencies]
glam = "0.33"
oxidros = { git = "https://github.com/jazi007/oxidros", rev = "566e2efdff31e39b372bab54fb75b2e836ba5ca7", features = ["zenoh"] }
cadrum = { version = "^0.8", optional = true }
comfy-table = { version = "7", optional = true }
serde = { version = "1", features = ["derive"], optional = true }
serde_yaml = { version = "0.9", optional = true }

[[bin]]
name = "assembly"
required-features = ["generator"]

[[bin]]
name = "headrest_mount"
required-features = ["generator"]

[[bin]]
name = "wheel"
required-features = ["generator"]

[[bin]]
name = "mount_and_motor"
required-features = ["generator"]

[[bin]]
name = "mount_motor_and_wheel"
required-features = ["generator"]

[lints.clippy]
all = "deny"
