# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, modulesPath, ... }:

{
  imports =
    [ (modulesPath + "/profiles/qemu-guest.nix")
    ];

  boot={
    kernelModules = [ ];
    extraModulePackages = [ ];
    initrd={
      kernelModules = [ ];
      availableKernelModules = [
        "sr_mod"
        "usbhid"
        "xhci_pci"
        "virtio_pci"
        "usb_storage"
      ];
    };
  };

  fileSystems = {
    "/boot" = {
       device = "/dev/disk/by-uuid/9F6B-90BC";
       fsType = "vfat";
       options = [ "fmask=0077" "dmask=0077" ];
      };

    "/" = {
       device = "/dev/disk/by-uuid/76c629c9-9468-47e8-bec8-32ea7e1830fd";
       fsType = "ext4";
      };
    };

  swapDevices =
    [ { device = "/dev/disk/by-uuid/ecdaeac0-7406-4672-bd91-2fe78e6ce5c0"; }
    ];

  # Enables DHCP on each ethernet and wireless interface. In case of scripted networking
  # (the default) this is the recommended approach. When using systemd-networkd it's
  # still possible to use this option, but it's recommended to use it in conjunction
  # with explicit per-interface declarations with `networking.interfaces.<interface>.useDHCP`.
  networking.useDHCP = lib.mkDefault true;
  # networking.interfaces.enp0s1.useDHCP = lib.mkDefault true;

  nixpkgs.hostPlatform = lib.mkDefault "aarch64-linux";
}
