[package]
name = "robot_control"
version = "0.1.0"
edition = "2021"

[dependencies]
robot_description = { path = "../robot_description" }
oxidros = { git = "https://github.com/jazi007/oxidros", rev = "566e2efdff31e39b372bab54fb75b2e836ba5ca7", features = ["zenoh"] }
rsruckig = "2.2.1"
tokio = { version = "1", features = ["full"] }
tracing = "0.1"

[lints.clippy]
all = "deny"
