/**:
  ros__parameters:
    local_frame: odom
    global_frame: odom
    robot_base_frame: base_link
    transform_tolerance: 0.2
    behavior_plugins: ["spin", "backup", "drive_on_heading", "wait"]
    spin:
      plugin: "nav2_behaviors::Spin"
    backup:
      plugin: "nav2_behaviors::BackUp"
    drive_on_heading:
      plugin: "nav2_behaviors::DriveOnHeading"
    wait:
      plugin: "nav2_behaviors::Wait"
    cycle_frequency: 10.0
    simulate_ahead_time: 0.0
    max_rotational_vel: 0.5
    min_rotational_vel: 0.1
    rotational_acc_lim: 1.0
    enable_stamped_cmd_vel: true
