CONFIG_WOLFSSH=y
CONFIG_WOLFSSH_SETTINGS_FILE="wolfssh_user_settings.h"

CONFIG_WOLFSSL=y
CONFIG_WOLFSSL_BUILTIN=y
CONFIG_WOLFSSL_SETTINGS_FILE="wolfssl_user_settings.h"

# NOTE: also include boot/posix.conf — wolfSSL's wc_port.h needs pthread
