[workspace]
name = "robot-ws"
channels = ["https://prefix.dev/robostack-lyrical", "https://prefix.dev/conda-forge"]
platforms = ["linux-aarch64"]

[dependencies]
ros-lyrical-ros2-control = "*"
ros-lyrical-ros2-controllers = "*"
ros-lyrical-twist-mux = "*"
ros-lyrical-rmw-zenoh-cpp = "*"
ros-lyrical-ros2run = "*"
ros-lyrical-rclpy = "*"
ros-lyrical-sensor-msgs = "*"
colcon-common-extensions = "*"
cxx-compiler = "*"
sysroot_linux-aarch64 = ">=2.28"
cmake = "*"
ninja = "*"
git = "*"

[pypi-dependencies]
adafruit-circuitpython-bno08x = "*"
adafruit-extended-bus = "*"

[tasks]
build = "colcon build --merge-install --cmake-args -GNinja"

[tasks.controller-manager]
cmd = "AMENT_PREFIX_PATH=$PIXI_PROJECT_ROOT/install:$AMENT_PREFIX_PATH LD_LIBRARY_PATH=$PIXI_PROJECT_ROOT/install/lib:$LD_LIBRARY_PATH ros2 run controller_manager ros2_control_node --ros-args -r ~/robot_description:=/robot_description --params-file $PIXI_PROJECT_ROOT/config/control.yaml --params-file $PIXI_PROJECT_ROOT/config/drivetrain.generated.yaml"

[tasks.twist-mux]
cmd = "ros2 run twist_mux twist_mux --ros-args --params-file $PIXI_PROJECT_ROOT/config/twist_mux.yaml -r cmd_vel_out:=/platform/cmd_vel"

[tasks.controller-spawner]
cmd = "AMENT_PREFIX_PATH=$PIXI_PROJECT_ROOT/install:$AMENT_PREFIX_PATH LD_LIBRARY_PATH=$PIXI_PROJECT_ROOT/install/lib:$LD_LIBRARY_PATH ros2 run controller_manager spawner joint_state_broadcaster diff_drive_controller --param-file $PIXI_PROJECT_ROOT/config/control.yaml --param-file $PIXI_PROJECT_ROOT/config/drivetrain.generated.yaml --controller-manager-timeout 60 --controller-ros-args '-r ~/cmd_vel:=/platform/cmd_vel'"

[tasks.bno085]
cmd = "python $PIXI_PROJECT_ROOT/src/imu_driver.py --ros-args -r __node:=imu_0 -r data:=/sensors/imu_0/data -r mag:=/sensors/imu_0/mag -r linear_acceleration:=/sensors/imu_0/linear_acceleration -r stability:=/sensors/imu_0/stability -r activity:=/sensors/imu_0/activity -r steps:=/sensors/imu_0/steps -r shake:=/sensors/imu_0/shake -r calibration_status:=/sensors/imu_0/calibration_status --params-file $PIXI_PROJECT_ROOT/config/imu_0.yaml"
