package providers

import (
	"github.com/pulumi/pulumi-github/sdk/v6/go/github"
	// "github.com/pulumi/pulumi/sdk/v3/go/pulumi/config"
	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
)

func GitHub(ctx *pulumi.Context, enable bool) error {
	if !enable {
		return nil
	}

	// cfg := config.New(ctx, "")
	// token := cfg.Get("github:token")

	// FIXME: * POST https://api.github.com/user/gpg_keys: 404 Not Found []
	//   _, err := github.NewUserGpgKey(ctx, "mfarabi619@gmail.com", &github.UserGpgKeyArgs{
	//   	ArmoredPublicKey: pulumi.String("-----BEGIN PGP PUBLIC KEY BLOCK-----\n mDMEaR5MBRYJKwYBBAHaRw8BAQdAFcxnY9PEwt8tHa1IagKgLxx7fXFHSioJce3Y\n P+/+QmG0Jk11bXRhaGluIEZhcmFiaSA8bWZhcmFiaTYxOUBnbWFpbC5jb20+iI4E\n ExYKADYWIQTLy0CAKAv3hRizBHswa5TaLOYZigUCaR5MBQIbAwQLCQgHBBUKCQgF\n FgIDAQACHgECF4AACgkQMGuU2izmGYqn8QEAlDnuRUk2VmlZysNG6MEE7VvRITPO\n Frfc6TKQOg+2mckA/0bEhuH5DXy2U8JQMfUkrEQSZ4dcvsFAoTeWh0Rva7oEuDgE\n aR5MBRIKKwYBBAGXVQEFAQEHQI8x2tLx0SF5HqDe+dIlUOTynrHK1vyYTfPnEcaH\n TXpMAwEIB4h4BBgWCgAgFiEEy8tAgCgL94UYswR7MGuU2izmGYoFAmkeTAUCGwwA\n CgkQMGuU2izmGYpSTgEAnRv5MHdDyMPvz+uQocGxkach8vaibYASmZUcSCvBzWQA\n /2IBEfo3yFg98z07OkkmiU4/T2Wg+vUhPo6CLJbd3AYH\n =e+V4\n -----END PGP PUBLIC KEY BLOCK-----"),
	//   })
	//   if err != nil {
	//   	return err
	//   }

	repository, err := github.NewRepository(ctx, "pulumi-example", &github.RepositoryArgs{
		Name:                pulumi.String("pulumi-example"),
		Visibility:          pulumi.String("private"),
		HomepageUrl:         pulumi.String("mfarabi.sh"),
		Description:         pulumi.String("Generated by Pulumi"),
		Fork:                pulumi.Bool(false),
		GitignoreTemplate:   pulumi.String("C++"),
		AllowAutoMerge:      pulumi.Bool(false),
		AllowMergeCommit:    pulumi.Bool(false),
		AllowRebaseMerge:    pulumi.Bool(true),
		AllowSquashMerge:    pulumi.Bool(false),
		AllowUpdateBranch:   pulumi.Bool(true),
		ArchiveOnDestroy:    pulumi.Bool(false),
		Archived:            pulumi.Bool(false),
		AutoInit:            pulumi.Bool(true),
		DeleteBranchOnMerge: pulumi.Bool(false),
		HasDiscussions:      pulumi.Bool(false),
		HasDownloads:        pulumi.Bool(true),
		HasIssues:           pulumi.Bool(true),
		HasProjects:         pulumi.Bool(false),
		HasWiki:             pulumi.Bool(false),
		IsTemplate:          pulumi.Bool(false),
		LicenseTemplate:     pulumi.String("GPL-3.0"),
		// SourceOwner: pulumi.String("MFarabi619"),
		// SourceRepo:  pulumi.String("MFarabi619"),
		// MergeCommitMessage:  pulumi.String("string"),
		//	Template: &github.RepositoryTemplateArgs{
		//		Owner:              pulumi.String("string"),
		//	Repository:         pulumi.String("string"),
		//	IncludeAllBranches: pulumi.Bool(false),
		//	},
		Topics: pulumi.StringArray{
			pulumi.String("pulumi"),
			pulumi.String("nix"),
		},
		VulnerabilityAlerts:      pulumi.Bool(false),
		WebCommitSignoffRequired: pulumi.Bool(false),
	})

	if err != nil {
		return err
	}

	// 	_, err = github.NewRepositoryCollaborator(ctx, "a_repo_collaborator", &github.RepositoryCollaboratorArgs{
	// 		Repository:                repository.Name,
	// 		PermissionDiffSuppression: pulumi.Bool(false),
	// 		Permission:                pulumi.String("admin"),
	// 		Username:                  pulumi.String("MFarabi619"),
	//	})

	//	if err != nil {
	//		return err
	//	}

	_, err = github.NewRepositoryFile(ctx, "README", &github.RepositoryFileArgs{
		Repository: repository.Name,
		Branch:     pulumi.String("main"),
		Content: pulumi.String(`* Title

      ** Subtitle

        **bold text**`),
		File:              pulumi.String("README.org"),
		CommitAuthor:      pulumi.String("Mumtahin Farabi"),
		CommitEmail:       pulumi.String("mfarabi619@gmail.com"),
		CommitMessage:     pulumi.String("docs(readme): create file"),
		OverwriteOnCreate: pulumi.Bool(true),
	})
	if err != nil {
		return err
	}

	return nil
}
