if("${ARCH}" STREQUAL "riscv")
  set(_zig_target "riscv32-freestanding-none")

  set(_features "generic_rv32")
  if(CONFIG_RISCV_ISA_EXT_M)
    string(APPEND _features "+m")
  endif()
  if(CONFIG_RISCV_ISA_EXT_A)
    string(APPEND _features "+a")
  endif()
  if(CONFIG_RISCV_ISA_EXT_C)
    string(APPEND _features "+c")
  endif()
  # Gate FP on CONFIG_FPU (kernel uses FP), not CONFIG_RISCV_ISA_EXT_F (HW has FP).
  # qemu_riscv32 sets the ISA bit but builds soft-float — mixing aborts the linker.
  if(CONFIG_FPU AND CONFIG_RISCV_ISA_EXT_F)
    string(APPEND _features "+f")
  endif()
  if(CONFIG_RISCV_ISA_EXT_ZICSR)
    string(APPEND _features "+zicsr")
  endif()
  if(CONFIG_RISCV_ISA_EXT_ZIFENCEI)
    string(APPEND _features "+zifencei")
  endif()
  set(_zig_mcpu "${_features}")
  unset(_features)

elseif("${ARCH}" STREQUAL "xtensa")
  set(_zig_target "xtensa-freestanding-none")
  if(CONFIG_SOC_SERIES_ESP32S3)
    set(_zig_mcpu "esp32s3")
  elseif(CONFIG_SOC_SERIES_ESP32S2)
    set(_zig_mcpu "esp32s2")
  elseif(CONFIG_SOC_SERIES_ESP32)
    set(_zig_mcpu "esp32")
  else()
    message(FATAL_ERROR "zephyr-lang-zig: unrecognized xtensa SOC series")
  endif()

else()
  message(FATAL_ERROR "zephyr-lang-zig: ARCH '${ARCH}' not supported (riscv32, esp32/s2/s3 only)")
endif()

set(ZIG_TARGET "${_zig_target}" CACHE INTERNAL "" FORCE)
set(ZIG_MCPU "${_zig_mcpu}" CACHE INTERNAL "" FORCE)
unset(_zig_target)
unset(_zig_mcpu)

message(STATUS "zephyr-lang-zig: target=${ZIG_TARGET} mcpu=${ZIG_MCPU}")
