CONFIG_SDHC=y
CONFIG_GPIO=y
CONFIG_SDIO_STACK=y
CONFIG_OH_MY_ZEPHYR=n
CONFIG_ESP_HOSTED_WIFI=y
CONFIG_NET_L2_ETHERNET=y
CONFIG_WIFI_INIT_PRIORITY=90

# Ask the DHCP server to broadcast its reply: the C6 bridge doesn't forward unicast.
CONFIG_NET_DHCPV4_ACCEPT_UNICAST=n
