CONFIG_NET_HOSTNAME="amoled"

CONFIG_ESPTOOLPY_OCT_FLASH=n
CONFIG_SPIRAM_MODE_OCT=y

CONFIG_HEAP_MEM_POOL_SIZE=32768

CONFIG_I2C=y
CONFIG_I2C_SHELL=y
CONFIG_GPIO_SHELL=y
CONFIG_INPUT_SHELL=y
CONFIG_INPUT_EVENT_DUMP=y
CONFIG_GPIO_HOGS_INIT_PRIORITY=60

CONFIG_RTC=y
CONFIG_RTC_SHELL=y

CONFIG_SENSOR=y
CONFIG_SENSOR_SHELL=y

CONFIG_MFD=y
CONFIG_FUEL_GAUGE=y

CONFIG_DISPLAY=y

CONFIG_SDHC=y
CONFIG_SDMMC_STACK=y
CONFIG_DISK_ACCESS=y
CONFIG_DISK_DRIVER_SDMMC=y
CONFIG_FILE_SYSTEM=y
CONFIG_FAT_FILESYSTEM_ELM=y
CONFIG_FILE_SYSTEM_SHELL=y
