CONFIG_NET_HOSTNAME="xiao-sense"

CONFIG_ESPTOOLPY_OCT_FLASH=n

# CONFIG_SQLITE=y

CONFIG_SDMMC_STACK=y
CONFIG_FS_FATFS_EXFAT=y

CONFIG_MCUMGR_GRP_FS=y
CONFIG_MCUMGR_GRP_FS_FILE_STATUS=y
CONFIG_MCUMGR_GRP_FS_HASH_SHA256=y
CONFIG_MCUMGR_GRP_FS_CHECKSUM_HASH=y
CONFIG_MCUMGR_GRP_FS_MAX_FILE_SIZE_4GB=y
CONFIG_MCUMGR_GRP_FS_CHECKSUM_IEEE_CRC32=y

CONFIG_FILE_SYSTEM=y
CONFIG_FILE_SYSTEM_MKFS=y
CONFIG_FILE_SYSTEM_SHELL_TEST_COMMANDS=y
CONFIG_FS_LOG_LEVEL_DBG=y
CONFIG_FS_FATFS_LFN=y
CONFIG_FS_FATFS_HAS_RTC=y
CONFIG_FS_FATFS_EXTRA_NATIVE_API=y
CONFIG_FAT_FILESYSTEM_ELM=y

CONFIG_HTTP_PARSER=y
CONFIG_HTTP_PARSER_URL=y
CONFIG_HTTP_SERVER=y
CONFIG_HTTP_SERVER_COMPRESSION=y
CONFIG_HTTP_SERVER_RESOURCE_WILDCARD=y
CONFIG_HTTP_SERVER_STACK_SIZE=8192
CONFIG_HTTP_SERVER_CLIENT_BUFFER_SIZE=1024
CONFIG_HTTP_SERVER_MAX_URL_LENGTH=512
CONFIG_EVENTFD=y
