;; -*- mode: eask; lexical-binding: t -*-

(package "kanban"
         "0.0.1"
         "Kanban board for GNU Emacs")

(website-url "https://github.com/MFarabi619/MFarabi619/modules/home/programs/emacs/extra/kanban")
(keywords "tools" "convenience")

(package-file "kanban.el")

(script "check" "eask lint checkdoc && eask compile && eask clean elc && eask test buttercup")

(development
 (depends-on "buttercup"))
