# [[file:../CONTRIBUTING.org::*\[\[https:/doc.rust-lang.org/cargo/reference/manifest.html#the-rust-toolchain-file\]\[rust-toolchain.toml\]\]][[[https://doc.rust-lang.org/cargo/reference/manifest.html#the-rust-toolchain-file][rust-toolchain.toml]]:1]]
[toolchain]
channel = "esp"
profile = "minimal"
# channel = "stable"

components = [
    "rustc",
    "cargo",
    "clippy",
    "rustfmt",
    "rust-src",
    "rust-analyzer",
    "rustfmt",
]

targets = [
    "thumbv6m-none-eabi",
    "thumbv7em-none-eabihf",
    "thumbv8m.main-none-eabihf",
    "riscv32imac-unknown-none-elf",
]
# [[https://doc.rust-lang.org/cargo/reference/manifest.html#the-rust-toolchain-file][rust-toolchain.toml]]:1 ends here
