CONFIG_MODEM=y
CONFIG_MODEM_STATS=y
CONFIG_MODEM_AT_SHELL=y

CONFIG_MODEM_CMUX_MTU=1500
CONFIG_MODEM_CELLULAR=y
CONFIG_MODEM_CELL_INFO=y
CONFIG_MODEM_CELLULAR_APN="m2minternet.apn" # or "rogersdefault.apn"
CONFIG_MODEM_CELLULAR_CHAT_BUFFER_SIZE=4096
CONFIG_MODEM_CELLULAR_UART_BUFFER_SIZES=2048
