/**:
  ros__parameters:
    use_stamped: true
    topics:
      joy:
        topic: joy_teleop/cmd_vel
        timeout: 0.5
        priority: 10
      external:
        topic: cmd_vel
        timeout: 0.5
        priority: 1
    locks:
      emergency_stop:
        topic: platform/emergency_stop
        timeout: 0.0
        priority: 255
      safety_stop:
        topic: platform/safety_stop
        timeout: 0.0
        priority: 254
